"""
coaches_data.py — Head coaches for the 2026 season (the built-in universe; all fictional).

Every coach's six ratings are generated around his team's Coach Skill,
seeded by his name so they're the same every new game. COACH_OVERRIDES
pins the ratings where a coach has a reputation; edit freely.
"""

HEAD_COACHES = {
    # SCC
    'Alabama': 'Carson Wexley',
    'Arkansas': 'Dalton Rourke',
    'East Alabama': 'Beau Hartsell',
    'Florida': 'Wade Lindqvist',
    'Georgia': 'Everett Kline',
    'Kentucky': 'Nolan Prewitt',
    'Bayou State': 'Remy Thibodeaux',
    'Mississippi State': 'Grady Pettigrew',
    'Missouri': 'Bryce Haldane',
    'Oklahoma': 'Jarrett Coyle',
    'Mississippi': 'Ashby Vance',
    'South Carolina': 'Corbin Talley',
    'Tennessee': 'Rhett Calloway',
    'Texas': 'Garrett Holloway',
    'Brazos': 'Lyle Ostrander',
    'Nashville': 'Preston Albee',
    # Continental
    'Illinois': 'Bram Lofgren',
    'Indiana': 'Silas Wendt',
    'Iowa': 'Mason Ehrlich',
    'Maryland': 'Theo Brannigan',
    'Michigan': 'Conrad Vail',
    'Michigan State': 'Duncan Pelletier',
    'Minnesota': 'Anders Thorsgaard',
    'Nebraska': 'Gunnar Pohl',
    'Lakeshore': 'Ellis Fairbanks',
    'Ohio State': 'Bennett Crowley',
    'Oregon': 'Kai Lindgren',
    'Pennsylvania': 'Wyatt Strand',
    'Tippecanoe': 'Hal Bergstrom',
    'New Jersey': 'Vincent Albanese',
    'Los Angeles': 'Marco Esquivel',
    'Southern California': 'Tate Morrow',
    'Washington': 'Rowan Hesketh',
    'Wisconsin': 'Torsten Haugen',
    # Seaboard
    'Boston': 'Declan Moriarty',
    'California': 'Julian Ashcroft',
    'Upcountry': 'Walker Brantley',
    'Durham': 'Simon Whitaker',
    'Florida State': 'Mateo Ferrante',
    'Atlanta': 'Harrison Vogt',
    'Louisville': 'Brooks Whitfield',
    'Miami': 'Luis Arrondo',
    'NC State': 'Curtis Greer',
    'North Carolina': 'Bradford Lyle',
    'Pittsburgh': 'Frank Kozlowski',
    'Dallas': 'Chandler Price',
    'Palo Alto': 'Hugh Kensington',
    'Syracuse': 'Carmine DeSantis',
    'Virginia': 'Philip Ashworth',
    'Blacksburg': 'Clayton Dunmore',
    'Winston-Salem': 'Graham Pettis',
    # Meridian
    'Arizona': 'Rafael Montoya',
    'Arizona State': 'Kendall Ruark',
    'Waco': 'Travis Keener',
    'Provo': 'Daniel Faleolo',
    'Cincinnati': 'Neil Brandt',
    'Colorado': 'Jace Whitlock',
    'Houston': 'Marcus Delane',
    'Iowa State': 'Owen Fjelstad',
    'Kansas': 'Lucas Tremont',
    'Kansas State': 'Cody Rasmussen',
    'Oklahoma State': 'Bo Kittredge',
    'Fort Worth': 'Rusty Calder',
    'Lubbock': 'Joel Mahaffey',
    'Orlando': 'Tyler Brennick',
    'Utah': 'Morgan Talbot',
    'West Virginia': 'Dale Shumate',
    # Federal
    'Hudson': 'Robert Kessler',
    'Charlotte': 'Derrick Sams',
    'East Carolina': 'Reid Kirkland',
    'Florida Atlantic': 'Andre Velasco',
    'Memphis': 'Antoine Belcher',
    'Chesapeake': 'William Hargrove',
    'North Texas': 'Jordan Kesey',
    'Montrose': 'Patrick Ellery',
    'South Florida': 'Darnell Wicks',
    'Philadelphia': 'Joe Castellano',
    'New Orleans': 'Andre Fontenot',
    'Tulsa': 'Clint Ballard',
    'Birmingham': 'Terrell Gaines',
    'San Antonio': 'Esteban Garza',
    # Coastal Plains
    'Appalachian State': 'Cole Ramsey',
    'Grand Strand': 'Shane Lockridge',
    'Georgia Southern': 'Wesley Crump',
    'Georgia State': 'Malik Henley',
    'Shenandoah': 'Lowell Prentice',
    'Huntington': 'Rex Stonecipher',
    'Norfolk': 'Kurt Ellison',
    'Arkansas State': 'Ty Hendrix',
    'Louisiana': 'Jules Broussard',
    'Ruston': 'Kyle Duhon',
    'Monroe': 'Mitch Arceneaux',
    'South Alabama': 'Corey Bledsoe',
    'Southern Miss': 'Rodney Pace',
    'Troy': 'Hank Lowry',
    # Lake Country
    'Akron': 'Glen Wozniak',
    'Muncie': 'Neal Overholt',
    'Bowling Green': 'Dean Halvorsen',
    'Buffalo': 'Paul Dziedzic',
    'Central Michigan': 'Ross Kaminski',
    'Eastern Michigan': 'Victor Szabo',
    'Kent State': 'Aaron Lundquist',
    'Miami (OH)': 'Stuart Fenwick',
    'Ohio': 'Brady Sorensen',
    'Sacramento State': 'Isaiah Tolbert',
    'Toledo': 'Roman Pacheco',
    'Massachusetts': 'Liam Dorsey',
    'Western Michigan': 'Evan Marchbanks',
    # Crossroads
    'Delaware': 'Martin Kowal',
    'Biscayne': 'Hector Ibarra',
    'Jacksonville State': 'Denny Rutledge',
    'Kennesaw State': 'Tremaine Hobbs',
    'Lynchburg': 'Josiah Breckin',
    'Middle Tennessee': 'Lonnie Gaither',
    'Missouri State': 'Wes Callender',
    'New Mexico State': 'Fernando Ruelas',
    'Huntsville': 'Bart Wilburn',
    'Western Kentucky': 'Shelby Akers',
    # Golden West
    'Boise State': 'Ryder Mulholland',
    'Colorado State': 'Ned Ostrowski',
    'Fresno State': 'Rubén Castañeda',
    'Oregon State': 'Calvin Dorr',
    'San Diego State': 'Tomas Quintero',
    'Texas State': 'Darius Kemp',
    'Utah State': 'Dallin Merrill',
    'Washington State': 'Jasper Kincaid',
    # High Country
    'Front Range': 'Mitchell Dorrance',
    "Hawai'i": 'Keoni Kahale',
    'Nevada': 'Boyd Halloran',
    'New Mexico': 'Rico Baca',
    'North Dakota State': 'Erik Sundberg',
    'Northern Illinois': 'Dale Kirchner',
    'San Jose State': 'Martin Okafor',
    'Las Vegas': 'Vince Fortunato',
    'El Paso': 'Joaquín Arellano',
    'Wyoming': 'Dustin Clay',
    # Independent
    'South Bend': 'Patrick Dunleavy',
    'Connecticut': 'Brendan Keough',
}

# Reputation-based pins (anything not listed is generated around Coach Skill).
COACH_OVERRIDES = {
    'Everett Kline': {'recruiting': 98, 'trench_dev': 94, 'db_dev': 96},
    'Bennett Crowley': {'recruiting': 94, 'passing_dev': 94},
    'Garrett Holloway': {'recruiting': 95, 'passing_dev': 95},
    'Remy Thibodeaux': {'recruiting': 92, 'passing_dev': 95},
    'Silas Wendt': {'recruiting': 74, 'passing_dev': 93, 'offense_dev': 92, 'trench_dev': 92, 'db_dev': 93},
    'Kai Lindgren': {'recruiting': 95, 'db_dev': 91, 'trench_dev': 90},
    'Patrick Dunleavy': {'recruiting': 93, 'db_dev': 91},
    'Luis Arrondo': {'recruiting': 92, 'trench_dev': 95},
    'Carson Wexley': {'recruiting': 88, 'passing_dev': 91},
    'Conrad Vail': {'recruiting': 76, 'trench_dev': 90, 'db_dev': 89},
    'Wyatt Strand': {'recruiting': 74, 'trench_dev': 88, 'offense_dev': 86},
    'Mason Ehrlich': {'recruiting': 62, 'trench_dev': 96, 'special_dev': 95},
    'Rhett Calloway': {'passing_dev': 91},
    'Jarrett Coyle': {'db_dev': 91},
    'Lyle Ostrander': {'db_dev': 89, 'trench_dev': 87},
    'Jace Whitlock': {'recruiting': 88, 'db_dev': 90},
    'Bradford Lyle': {'recruiting': 70, 'db_dev': 92, 'special_dev': 90},
    'Darnell Wicks': {'recruiting': 90, 'passing_dev': 93},
    'Julian Ashcroft': {'recruiting': 90, 'trench_dev': 86},
    'Joel Mahaffey': {'recruiting': 88},
    'Walker Brantley': {'recruiting': 88},
    'Bryce Haldane': {'recruiting': 84},
    'Kendall Ruark': {'passing_dev': 88},
    'Preston Albee': {'db_dev': 85},
    'Brooks Whitfield': {'passing_dev': 88},
    'Robert Kessler': {'offense_dev': 85, 'recruiting': 58},
}


# Offensive scheme, defensive scheme, aggression (None = generated).
COACH_STYLES = {
    'Robert Kessler': ('Triple Option', '4-3 Zone', 45),
    'William Hargrove': ('Triple Option', 'Pressure 3-4', 55),
    'Mitchell Dorrance': ('Triple Option', 'Pressure 3-4', 45),
    'Patrick Ellery': ('Triple Option', None, 55),
    'Andre Velasco': ('Air Raid', None, 70),
    'Grady Pettigrew': ('Air Raid', None, 65),
    'Rusty Calder': ('Air Raid', None, 60),
    'Darius Kemp': ('Air Raid', None, 70),
    'Kyle Duhon': ('Air Raid', None, 60),
    'Bo Kittredge': ('Air Raid', None, 65),
    'Tate Morrow': ('Air Raid', None, 65),
    'Tomas Quintero': ('Air Raid', '3-3-5 Stack', 80),
    'Jace Whitlock': ('Air Raid', 'Multiple Man', 60),
    'Mason Ehrlich': ('Pro Style', '4-2-5 Quarters', 25),
    'Bram Lofgren': ('Smashmouth', 'Pressure 3-4', 45),
    'Conrad Vail': ('Smashmouth', 'Multiple Man', 45),
    'Everett Kline': ('Pro Style', 'Pressure 3-4', 60),
    'Remy Thibodeaux': ('Spread RPO', 'Multiple Man', 85),
    'Garrett Holloway': ('Pro Style', 'Multiple Man', 60),
    'Bennett Crowley': ('Spread RPO', '4-2-5 Quarters', 55),
    'Silas Wendt': ('Pro Style', '4-2-5 Quarters', 70),
    'Kai Lindgren': ('Spread RPO', 'Pressure 3-4', 80),
    'Patrick Dunleavy': ('Pro Style', '4-2-5 Quarters', 55),
    'Carson Wexley': ('West Coast', 'Multiple Man', 60),
    'Rhett Calloway': ('Spread RPO', None, 70),
    'Jarrett Coyle': ('Spread RPO', 'Pressure 3-4', 65),
    'Bradford Lyle': ('Pro Style', 'Multiple Man', 40),
    'Lyle Ostrander': ('Pro Style', '4-2-5 Quarters', 50),
    'Luis Arrondo': ('Pro Style', '4-2-5 Quarters', 45),
    'Kendall Ruark': ('Spread RPO', None, 85),
    'Wyatt Strand': ('Pro Style', '3-3-5 Stack', 50),
    'Dale Shumate': ('Spread RPO', '3-3-5 Stack', 70),
    'Brooks Whitfield': ('Pro Style', None, 60),
    'Rowan Hesketh': ('West Coast', None, 60),
    'Travis Keener': (None, 'Pressure 3-4', 50),
    'Anders Thorsgaard': ('Pro Style', None, 45),
    'Gunnar Pohl': ('Pro Style', None, 50),
    'Torsten Haugen': ('Pro Style', 'Pressure 3-4', 45),
    'Vincent Albanese': ('Pro Style', None, 40),
    'Frank Kozlowski': (None, '4-3 Zone', 50),
    'Walker Brantley': ('Spread RPO', '4-3 Zone', 50),
    'Dallin Merrill': (None, 'Pressure 3-4', 45),
    'Josiah Breckin': ('Spread RPO', None, 70),
    'Vince Fortunato': ('Spread RPO', None, 55),
    'Tyler Brennick': ('Spread RPO', None, 60),
    'Simon Whitaker': (None, 'Pressure 3-4', 75),
    'Ned Ostrowski': ('Pro Style', None, 50),
    'Joel Mahaffey': ('Spread RPO', 'Multiple Man', 70),
    'Cody Rasmussen': ('Spread RPO', None, 55),
    'Darnell Wicks': ('Spread RPO', None, 60),
    'Beau Hartsell': ('Spread RPO', None, 75),
    'Ashby Vance': ('Spread RPO', 'Multiple Man', 65),
    'Wade Lindqvist': ('Pro Style', '4-2-5 Quarters', 60),
}
