"""
gameday_more.py — Phase 2 content for Campus Countdown. Everything here is merged into
the pools in gameday_scenes.py and gameday_cast.py at import time.

Same rules as gameday_scenes.py: every scene reads top to bottom as one
conversation, and every reply answers the line before it.
"""

STORY_MORE = {
    "rivalry": [  # {riv}
        [("host", "{defender}, you played in a rivalry like {riv}. What's the week like?"),
         ("defender", "You can't go to class. Everybody on campus wants to talk to you about it. You eat lunch in "
                      "the football building just to get away from it."),
         ("host", "And Saturday?"), ("defender", "Saturday you finally get to hit somebody about it.")],
        [("boom", "My favorite thing about {riv}: the moms."), ("host", "The moms?"),
         ("boom", "Look out there. There are moms in the front row who'd tackle a mascot for this game."),
         ("crowd", "(roaring)"), ("host", "There are, actually.")],
        [("coach", "You know what I used to tell my team the week of a game like this? Nothing."),
         ("film", "Nothing?"), ("coach", "Nothing. They already knew. Any speech I gave was for me."),
         ("host", "That's the most honest thing you've ever said on this show."), ("coach", "Don't get used to it.")],
        [("film", "{riv} breaks every model I have. Every one."), ("host", "Why?"),
         ("film", "Because the team that's better on paper plays tight, and the team that's worse plays free."),
         ("coach", "That's not a model, {film_first}. That's football.")],
        [("host", "What's the best moment you ever saw in a game like {riv}, Coach?"),
         ("coach", "Walk-on. Fourth quarter. Blocked a punt. He never played another meaningful snap in his life."),
         ("boom", "And?"), ("coach", "And he's never bought a drink in that town since.")],
        [("defender", "The thing nobody tells you: the players know each other. High school teammates. Camp "
                      "roommates. Half of them text all week."),
         ("host", "Trash talk?"), ("defender", "Some. Mostly pictures of old high school photos. That's the real "
                                                "trash talk.")],
        [("host", "What's at stake in {riv} this year beyond the obvious?"),
         ("film", "Recruiting. Every kid in this region is watching. The winner gets the last word in living rooms "
                  "all winter."),
         ("coach", "That's true. I won recruits off this game. Lost a few, too.")],
        [("boom", "If {h} wins today I'm staying here. Buying a house."), ("host", "You said that last week."),
         ("boom", "I have a lot of houses, {host}."), ("crowd", "(laughter)")],
    ],
    "unbeaten": [
        [("host", "Somebody's perfect season ends today. {coach}, how do you prepare for that?"),
         ("coach", "You don't talk about the record. Ever. The second you start protecting a zero, you play scared."),
         ("defender", "We had a rule — nobody could say the word 'undefeated' in the building."),
         ("host", "What happened if you did?"), ("defender", "Extra conditioning. And a lot of dirty looks.")],
        [("film", "What stands out to me: neither of these teams has trailed in the fourth quarter much this year."),
         ("host", "So nobody's been tested."), ("film", "Nobody's been tested. Today one of them gets tested, and "
                                                         "we find out how they handle it.")],
        [("boom", "Two teams that haven't lost! I'm so happy I could cry, {host}."),
         ("host", "Please don't."), ("boom", "Too late."), ("crowd", "(cheering)")],
        [("defender", "The team that's been winning pretty is in trouble today. Pretty doesn't survive this."),
         ("film", "Which one's been winning pretty?"), ("defender", "You tell me. You're the film guy."),
         ("film", "...I'll tell you at the picks."), ("defender", "Now you know how he feels.")],
        [("host", "What does a loss today mean for the loser's season?"),
         ("film", "Honestly? Not much, as long as it's close. The format forgives one loss."),
         ("coach", "The format does. The fans don't. Neither do the players."),
         ("host", "So, emotionally—"), ("coach", "Emotionally it's a funeral. Mathematically it's fine.")],
        [("coach", "When I had an undefeated team, the hardest part was practice. Kids stop listening when they "
                   "haven't lost."),
         ("boom", "How'd you fix it?"), ("coach", "I lost my temper. Constantly. On purpose.")],
    ],
    "top10": [
        [("host", "{film}, top-ten matchups — do they live up to it?"),
         ("film", "About half the time. The other half, one team is overrated and we find out by halftime."),
         ("host", "Which half is this one?"), ("film", "I think this one's real. Both of these teams have earned it.")],
        [("coach", "The biggest difference in games like this is the second quarter."), ("host", "Why the second?"),
         ("coach", "Everybody scripts the first fifteen plays. The second quarter is where coaches actually coach.")],
        [("defender", "Top ten versus top ten, the defense that tackles better wins. That's it."),
         ("boom", "Tackling? That's your whole analysis?"),
         ("defender", "Missed tackles turn into touchdowns in games like this. So yes, {boom_first}."),
         ("boom", "...That's actually pretty good.")],
        [("host", "The playoff committee chair is here today, I'm told."),
         ("boom", "Where? Let me talk to him!"), ("host", "Absolutely not."), ("crowd", "(laughter)")],
        [("film", "Neither of these teams is used to trailing. Somebody's about to find out what it's like "
                  "to play from behind."),
         ("coach", "And that's where you find out about a quarterback.")],
    ],
    "ranked": [
        [("host", "{A} and {H}, both ranked. {coach}, what do you want to see?"),
         ("coach", "Composure. Ranked teams expect to win. The one that stays calm when it gets tight wins."),
         ("defender", "And somebody always gets tight.")],
        [("film", "This is a sneaky good game. It's not getting the attention some others are."),
         ("boom", "It's getting OUR attention!"), ("film", "It's getting our attention, yes."),
         ("host", "Which is the only attention that matters.")],
        [("defender", "I think one of these teams is a lot better than its ranking."),
         ("host", "Which one?"), ("defender", "The one I pick."), ("crowd", "(laughter)")],
    ],
    "upset_alert": [  # {fav} {dog} {fav_rank}
        [("defender", "No. {fav_rank} {fav} is walking into a trap. {dog} has nothing to lose."),
         ("film", "The numbers don't love {dog}."), ("defender", "Numbers don't play on the road."),
         ("film", "...That doesn't even make sense."), ("defender", "It will tonight.")],
        [("host", "{dog} is unranked, and the crowd here couldn't care less."), ("crowd", "(roaring)"),
         ("boom", "You hear that, {fav}? You HEAR that?"), ("host", "I don't think they can hear you, {boom_first}."),
         ("boom", "They can hear me.")],
        [("film", "What does {dog} need to pull it off? Two things: win on third down and don't give up the big play."),
         ("coach", "And a little luck. You always need a little luck."),
         ("film", "Luck isn't in my model."), ("coach", "It's in every model, son.")],
        [("host", "When's the last time you saw a ranked team come in here and lose?"),
         ("defender", "It happens more than people think. Road games in college football are hard. Kids are kids."),
         ("coach", "I lost one of those once. Ranked in the top ten. Worst bus ride of my life.")],
        [("boom", "I have a confession. I've picked {dog} in my head all week."), ("host", "In your head?"),
         ("boom", "My heart and my head agree for once."), ("film", "That's never happened.")],
    ],
    "win_streak": [  # {team} {n}
        [("film", "During this {n}-game run, {team} has gotten better on third down every single week."),
         ("coach", "That's coaching. That's the staff finding answers."),
         ("host", "What stops it?"), ("coach", "A team that makes them uncomfortable. Somebody has to hit them first.")],
        [("host", "{n} straight for {team}. {defender}, what's the danger of a streak?"),
         ("defender", "You start thinking you can't lose. Then you stop doing the little things."),
         ("host", "Are they doing the little things?"), ("defender", "So far. That's what's impressive.")],
        [("boom", "Every week I pick against {team}, and every week they make me look stupid."),
         ("host", "So you're picking them today?"), ("boom", "Absolutely not. Today's the day."),
         ("film", "He said that last week.")],
        [("coach", "I had a streak like that once. The locker room gets quiet in a good way."),
         ("host", "Quiet?"), ("coach", "Nobody's worried about anything. Everybody just works.")],
    ],
    "skid": [  # {team} {n}
        [("defender", "{n} straight losses for {team}. At some point you have to look in the mirror."),
         ("coach", "The mirror doesn't tackle anybody. You have to change something they can see on the field."),
         ("host", "Like what?"), ("coach", "Start different people. Nothing wakes up a locker room like the depth chart.")],
        [("host", "{team} has dropped {n} in a row. Is today the day it ends?"),
         ("boom", "YES. I believe in them."), ("film", "Based on what?"), ("boom", "Based on belief, {film_first}."),
         ("film", "That's circular."), ("boom", "It's a circle of LOVE.")],
        [("film", "The tape on {team} during this skid: they're starting slow. They've trailed in the first quarter "
                  "in every loss."),
         ("coach", "That's preparation. That's on the coaches, not the players."),
         ("host", "Harsh."), ("coach", "It's the job. I said it about myself, too.")],
        [("coach", "Losing streaks are contagious. The veterans have to stop it — the coaches can't."),
         ("defender", "Agreed. When we lost three straight, a senior stood up in the meeting room and said one sentence."),
         ("host", "What was it?"), ("defender", "I can't say it on television.")],
    ],
    "riser": [  # {team} {was} {now}
        [("film", "{team} went from {was} to {now}, and I think they're still underrated."),
         ("host", "Still?"), ("film", "Look at who they've beaten. The voters are catching up slowly."),
         ("boom", "The voters are always slow."), ("film", "That's the one thing we agree on.")],
        [("host", "{team} up to No. {now}. {coach}, does the jump in the poll matter to a locker room?"),
         ("coach", "They'll say it doesn't. They all check their phones Sunday morning."),
         ("defender", "Every single one. I checked mine before I brushed my teeth.")],
        [("defender", "A jump like that puts a target on you. Every opponent circles you now."),
         ("host", "Starting today."), ("defender", "Starting today.")],
    ],
    "faller": [  # {team} {was} {now}
        [("host", "{team} dropped from No. {was} to {now}. {film}, overreaction?"),
         ("film", "A little. One loss doesn't make you a different team. But it did expose something."),
         ("host", "What?"), ("film", "The offensive line. It's been a problem all year. Everybody saw it last week.")],
        [("coach", "After a drop like that, the coach's job is to make the week feel normal."),
         ("boom", "Normal? They just got knocked out of the top ten!"),
         ("coach", "That's exactly why it has to feel normal, {boom_first}.")],
        [("boom", "If I were {team} I'd have the poll printed out and taped to every locker."),
         ("defender", "Some teams do that."), ("boom", "The GOOD teams do that.")],
    ],
    "bounce_back": [  # {team} {opp} {score}
        [("host", "{team} lost to {opp}, {score}, last week. {coach}, how do you handle Monday after that?"),
         ("coach", "You watch the film together. The whole team. Every bad play, out loud."),
         ("defender", "That's the worst meeting of the year. Nobody talks."),
         ("coach", "Nobody should talk. That's the point.")],
        [("film", "What went wrong for {team} last week wasn't effort. It was execution in the red zone."),
         ("host", "Fixable in a week?"), ("film", "Red zone is fixable in a week. Effort isn't. So that's good news.")],
        [("boom", "{team} is MAD this week, {host}. I can feel it from here."),
         ("host", "They're not even here, {boom_first}."), ("boom", "I can feel it from wherever they are.")],
        [("defender", "The {score} loss to {opp} — that'll be on the wall in their facility all week."),
         ("coach", "Or the coach will ban anybody from mentioning it. Two schools of thought."),
         ("host", "Which were you?"), ("coach", "Wall. Every time.")],
    ],
}

STORY_MORE_2 = {
    "hot_seat": [  # {team} {coach} {rec}
        [("host", "{coach} and {team} are {rec}, and the seat's getting warm. {coach_cast}, you've been there."),
         ("coach", "Every coach has been there. The ones who say they haven't are lying or haven't coached long."),
         ("host", "What do you do?"), ("coach", "You stop reading. You stop listening. You coach the next practice.")],
        [("film", "The thing about {team}: they lose close. The tape is better than the record."),
         ("defender", "Close doesn't count, {film_first}."), ("film", "It should, a little."),
         ("defender", "It doesn't. Ask any coach who got fired after losing six games by a field goal.")],
        [("boom", "I want to say something nice about {coach}."), ("host", "Go ahead."),
         ("boom", "...I'm thinking."), ("crowd", "(laughter)"), ("boom", "He dresses well! He dresses VERY well.")],
        [("defender", "The players know when the seat's hot. Some of them play harder for the coach."),
         ("host", "And the others?"), ("defender", "The others are already looking at the transfer portal.")],
        [("host", "What does {coach} need today?"),
         ("coach", "A signature win. Something the athletic director can point to and say 'see, it's coming.'"),
         ("film", "And if not?"), ("coach", "Then the AD starts making phone calls. Quietly.")],
    ],
    "new_coach": [  # {team} {coach} {rec}
        [("host", "{coach} is in year one at {team}. They're {rec}. {coach_cast}, how do you judge a first-year coach?"),
         ("coach", "Not by the record. By whether the players are playing hard in the fourth quarter."),
         ("film", "And they are. {team} has been better late in games than early."),
         ("coach", "That's the sign. That's a staff that's getting through.")],
        [("defender", "New coach, new culture. The first thing you notice is how they practice."),
         ("host", "You can see that on TV?"), ("defender", "You can see it in how they tackle. Tackling is practice.")],
        [("boom", "I love a new coach! New energy! New everything!"), ("coach", "New problems."),
         ("boom", "New PROBLEMS! I love those too!")],
    ],
    "coach_return": [  # {team} {coach} {old}
        [("host", "{coach} coached at {old}. Now he's across the field from them."),
         ("defender", "He recruited half of their seniors. He sat in their living rooms."),
         ("coach", "And some of those kids are going to want to prove he was wrong to leave."),
         ("host", "Or right to recruit them."), ("coach", "Either way, they're playing harder today.")],
        [("film", "The scheme advantage is real. He built part of that playbook."),
         ("coach", "They'll have changed the signals. Everybody changes the signals."),
         ("film", "Signals, sure. You can't change who your players are.")],
        [("boom", "If I left a job and came back to play them, I'd wear a disguise."),
         ("host", "A disguise?"), ("boom", "Fake mustache. Big sunglasses. They'd never know."),
         ("defender", "He'd be the only guy on the sideline in sunglasses."), ("boom", "EXACTLY.")],
    ],
    "injury": [  # {team} {player} {pos}
        [("film", "Losing {player} changes {team}'s whole plan. They'll have to simplify."),
         ("coach", "Simplifying isn't bad. Some of the best games I ever coached were with a backup."),
         ("host", "Why?"), ("coach", "Because nobody expected anything. The kids played loose.")],
        [("defender", "When a star goes down, the rest of the roster finds out who they are."),
         ("host", "Does {team} have the depth?"), ("defender", "We're about to find out, and so are they.")],
        [("host", "{player} is out for {team}. {boom}, what's your read?"),
         ("boom", "Somebody's getting a chance of a lifetime today. Somebody's mom is about to cry."),
         ("host", "That's... actually a sweet way to put it."), ("boom", "I have layers, {host}.")],
    ],
    "heisman": [  # {team} {player} {hrank} {stats}
        [("film", "{player}'s numbers — {stats} — are great, but watch how he plays when it's tight."),
         ("host", "What do you see?"), ("film", "He slows down. Everybody else speeds up. That's the gift."),
         ("coach", "You can't coach that. You find it or you don't.")],
        [("defender", "If I'm defending {player}, I'm hitting him early. Every chance I get. Legally."),
         ("host", "Legally."), ("defender", "Mostly legally.")],
        [("boom", "I've already written my Golden Helmet speech for {player}."), ("host", "You're not voting, {boom_first}."),
         ("boom", "I'm writing it FOR him. In case he needs one.")],
        [("host", "No. {hrank} in our Golden Helmet poll. What does he need today?"),
         ("film", "A moment. Voters remember one play more than a whole stat line."),
         ("coach", "And a win. Nobody wins a Golden Helmet in a loss this late in the year.")],
    ],
    "qb_duel": [  # {hqb} {aqb} {hstats} {astats}
        [("coach", "When I had to prepare for a quarterback like {aqb}, I lost sleep."),
         ("host", "And {hqb}?"), ("coach", "Same. Different reasons. One beats you with his arm, one beats you with his legs."),
         ("film", "Actually both beat you with their arms."), ("coach", "Then I lost more sleep than I thought.")],
        [("film", "{hqb} is {hstats}. {aqb} is {astats}. I'd take either one."),
         ("defender", "You have to pick one, {film_first}."), ("film", "I'll pick one when it counts.")],
        [("boom", "Quarterback duel! Shootout! Fireworks!"), ("defender", "Or two great defenses make them both "
                                                                           "look average."),
         ("boom", "Why would you say that on a Saturday morning?")],
    ],
    "shootout": [  # {hppg} {appg}
        [("film", "{hppg} and {appg} points a game. First to forty wins."),
         ("defender", "Or first to get one stop. I keep saying it."), ("host", "You do keep saying it."),
         ("defender", "Because it keeps being true.")],
        [("boom", "I'm predicting a hundred combined points."), ("coach", "That's not a prediction, that's a wish."),
         ("boom", "Wishes come true, Coach.")],
    ],
    "defense_duel": [  # {hpapg} {apapg}
        [("coach", "Two defenses giving up {hpapg} and {apapg}. This is my kind of football."),
         ("boom", "Your kind of football is boring, Coach."), ("coach", "My kind of football won championships.")],
        [("film", "The first team to twenty-one wins this game. Maybe the first to fourteen."),
         ("defender", "Now we're talking.")],
    ],
    "conf_race": [  # {conf} {hcrec} {acrec}
        [("host", "In the {conf}: {h} at {hcrec}, {a} at {acrec}. {film}?"),
         ("film", "Winner's the favorite for the title game. Loser needs somebody else to lose."),
         ("defender", "And nobody ever loses when you need them to.")],
        [("coach", "Conference titles are what you hang in the building. Playoffs are nice. Titles are forever."),
         ("boom", "Can you hang a playoff?"), ("coach", "You can hang a banner."), ("boom", "Then hang BOTH.")],
    ],
    "playoff": [
        [("host", "The playoff picture runs right through this game."),
         ("film", "The winner is almost a lock to host a first-round game on campus. The loser could be on the road."),
         ("coach", "Home playoff game in December. That's worth everything."),
         ("boom", "Can WE go to that one?"), ("host", "We'll see, {boom_first}.")],
        [("defender", "Every play today is a playoff play. You have to coach it that way."),
         ("coach", "And play it that way. No wasted downs.")],
    ],
    "revenge": [  # {winner} {loser} {ws} {ls} {year}
        [("defender", "{loser} lost this game {ws}-{ls} in {year}. I promise you somebody in that locker room "
                      "remembers every snap."),
         ("film", "The tape from that game is probably playing on a loop in their building."),
         ("coach", "It was in mine. You make them watch the worst plays until they're sick of them.")],
        [("host", "Revenge game for {loser}. {boom}, does revenge win football games?"),
         ("boom", "Revenge wins EVERYTHING, {host}."), ("film", "Revenge doesn't block anybody."),
         ("boom", "Revenge blocks EVERYBODY.")],
    ],
    "rematch": [  # {winner} {loser} {ws} {ls} {year}
        [("film", "{winner} won the last meeting, {ws}-{ls}, in {year}. Different rosters, but the same coaches' "
                  "tendencies."),
         ("coach", "Tendencies don't change much. I still call the same play on third and short I called in 1990."),
         ("host", "Really?"), ("coach", "I'm retired, {host}. I call it in my head.")],
    ],
    "goal_rival": [  # {team} {rival}
        [("host", "The athletic director at {team} put beating {rival} on the list of program goals."),
         ("boom", "In WRITING?"), ("host", "In writing."), ("coach", "That's a lot of pressure to put in writing."),
         ("defender", "That's a lot of pressure period.")],
        [("film", "When the AD writes down a rival's name, every coach in that building feels it."),
         ("coach", "You feel it in the grocery store. You feel it at church.")],
    ],
    "first_visit": [
        [("host", "First time Campus Countdown's ever been here. {defender}, what's that mean for a program?"),
         ("defender", "It means you arrived. Every high school kid in this state is watching this show right now."),
         ("coach", "And the ones who've never heard of {h} just did.")],
        [("boom", "First Campus Countdown in {town}! I'm going to remember this forever."),
         ("host", "You say that everywhere."), ("boom", "And I remember them ALL, {host}.")],
    ],
    "return_visit": [
        [("host", "Welcome back to {town}. Last time we were here was {last_year}."),
         ("film", "And the team's changed a lot since then. Different quarterback, different defense."),
         ("defender", "Same crowd, though."), ("crowd", "(roaring)"), ("defender", "Exactly the same crowd.")],
    ],
    # ── new storyline kinds ──
    "trap": [  # {team} {next}
        [("host", "{team} plays {next} next week. {coach_cast}, is this a trap game?"),
         ("coach", "Every coach says they don't look ahead. Every player does."),
         ("film", "The schedule-makers did {team} no favors."),
         ("coach", "That's why you tell your team the next game doesn't exist.")],
        [("defender", "{team} has {next} next week. You can't tell me that's not on their minds."),
         ("boom", "It's on MY mind and I don't even play for them."),
         ("host", "Everything's on your mind, {boom_first}."), ("boom", "It's a busy mind.")],
    ],
    "visit_curse": [  # {h} lost the last time Campus Countdown came
        [("host", "A little history — the last time Campus Countdown came to {town}, {h} lost."),
         ("crowd", "(booing)"), ("boom", "Don't boo US! We didn't play!"),
         ("host", "Some people call it the Campus Countdown curse."), ("film", "It's not a curse. It's a sample size of one.")],
        [("defender", "Last time we were here, {h} lost. The fans remember."),
         ("boom", "I've been apologizing all morning."), ("host", "To who?"),
         ("boom", "Everybody. The barbecue guy. A lady with a dog. Everybody.")],
    ],
    "bowl_push": [  # {team} {rec}
        [("host", "{team} is {rec}, one win from bowl eligibility."),
         ("coach", "Don't underestimate that. A bowl game means fifteen extra practices. That's next year's team."),
         ("film", "The young players get more reps in December than they did all season.")],
        [("boom", "One more win and {team} goes BOWLING!"), ("defender", "Every senior on that team wants one more game."),
         ("boom", "One more game! One more trip! One more buffet!")],
    ],
    "big_favorite": [  # {fav} {dog}
        [("host", "{fav} is a big favorite today. {boom}, you like {dog}, don't you?"),
         ("boom", "I like everybody, {host}. I like {dog} a LITTLE more today."),
         ("film", "The numbers say it's not close."), ("boom", "The numbers don't know about hope.")],
        [("coach", "Games like this are about not playing down to the opponent. That's harder than it sounds."),
         ("defender", "Everybody says they'll take it seriously. Then it's 10-10 at halftime.")],
    ],
}

OPENERS_MORE = {
    "default": [
        [("host", "Good morning from {town}! {A} at {H}, and the line to get on this lawn went around the block."),
         ("defender", "I saw people in sleeping bags at midnight. Sleeping bags!"),
         ("boom", "I was one of them."), ("host", "You were in a hotel, {boom_first}."), ("boom", "Spiritually, I was out there.")],
        [("crowd", "\"{chant}\""), ("host", "That's the sound of {town} on a Saturday morning. Welcome to Campus Countdown!"),
         ("film", "I've been looking forward to this matchup since the schedule came out."),
         ("host", "You say that about every matchup."), ("film", "I look forward to a lot of things, {host}.")],
        [("host", "Welcome to Campus Countdown, live from {stadium}!"), ("coach", "I coached here once. Visiting team."),
         ("host", "How'd it go?"), ("coach", "We don't need to get into it."), ("crowd", "(cheering)")],
        [("host", "Good morning, everybody. We're in {town}, and the coffee is strong and the crowd is stronger."),
         ("boom", "I've had four coffees, {host}."), ("host", "We can tell."), ("crowd", "(laughter)")],
        [("crowd", "(roaring)"), ("host", "{A}, {arec}. {H}, {hrec}. And {town} is wide awake. It's Campus Countdown!"),
         ("defender", "{host}, I don't think anybody in this town has slept in two days."),
         ("host", "Neither have you."), ("defender", "I'm a professional.")],
        [("host", "Welcome to Campus Countdown from {town}! {film}, you got in late last night?"),
         ("film", "Flight got delayed. I watched film on the plane."), ("boom", "Of course he did."),
         ("film", "I watched it twice, actually.")],
        [("boom", "GOOD MORNING, {TOWN}!"), ("crowd", "(roaring)"), ("host", "That's my job, {boom_first}."),
         ("boom", "I got excited."), ("host", "Good morning from {town}, everybody. {A} at {H}.")],
    ],
    "rivalry": [
        [("host", "Good morning from {town}! It's {riv} week, and nobody here has talked about anything else in "
                  "seven days."),
         ("defender", "Walked into a restaurant last night — three separate tables arguing about this game."),
         ("host", "Did you break it up?"), ("defender", "I picked a side. Made it worse.")],
        [("crowd", "\"{chant}\""), ("host", "{riv}. Nothing else needs to be said."),
         ("boom", "Can I say something anyway?"), ("host", "No."), ("crowd", "(laughter)")],
        [("host", "Welcome to {riv}! {coach}, what's the week like inside the building?"),
         ("coach", "Quiet. Nobody jokes the week of a rivalry game. Even the equipment guys stop smiling."),
         ("boom", "That sounds miserable."), ("coach", "It's the best week of the year.")],
    ],
    "opener": [
        [("crowd", "(roaring)"), ("host", "We're back! College football is back! Good morning from {town}!"),
         ("defender", "I've been counting down since January."), ("film", "I've been counting down since the "
                                                                          "title game ended."),
         ("boom", "I never stopped counting.")],
        [("host", "Week one. Everybody's undefeated, everybody's got a Golden Helmet candidate, and everybody's happy."),
         ("coach", "Enjoy it. It never lasts past October."), ("host", "Always the optimist, Coach.")],
    ],
    "first_visit": [
        [("host", "History in {town} — Campus Countdown's first ever visit!"), ("crowd", "(deafening)"),
         ("film", "They earned this. {h} has been building toward a day like this for years."),
         ("boom", "I've never been to {town} and I already want to retire here.")],
    ],
    "return_visit": [
        [("host", "Welcome back to {town}! It's been since {last_year}."),
         ("coach", "Too long. This is one of the best crowds in the country."),
         ("crowd", "(roaring)"), ("coach", "See? They agree with me.")],
    ],
    "postseason": [
        [("host", "The {round}. No more second chances. Good morning from {town}!"),
         ("defender", "This is when legacies get made. Nobody remembers who won in September."),
         ("film", "Everybody remembers who won in December.")],
        [("crowd", "(roaring)"), ("host", "It's the {round}! {A} and {H}!"),
         ("coach", "Every coach in America would trade places with these two staffs today."),
         ("boom", "I'd trade places with the mascots!")],
    ],
}

SIGNS_MORE = {
    "jab": ["{A} FANS: THE EXIT IS BEHIND YOU", "{AN}: THE BUS LEAVES AT HALFTIME", "{A} PEAKED IN THE PREGAME",
            "HEY {A}: WELCOME TO THE BIG LEAGUES", "{A}'S BUS IS DOUBLE PARKED", "WE CAME FOR {A}'S LUNCH MONEY",
            "{A} FANS, ASK US FOR DIRECTIONS HOME", "{A} RECRUITS: WE SEE YOU WATCHING",
            "{A} COULDN'T FIND {TOWN} ON A MAP LAST YEAR", "THE {AN} TOOK A WRONG TURN",
            "{A}: GOOD LUCK HEARING YOUR SNAP COUNT", "WHO INVITED {A}?", "SORRY {A}, WE'RE NOT SORRY",
            "{A}: YOUR SEASON ENDS IN {TOWN}", "{A} FANS PLEASE KEEP HANDS INSIDE THE VEHICLE",
            "I CAME TO WATCH {A} LOSE. AND FOR THE NACHOS."],
    "hype": ["{TOWN} DOESN'T SLEEP ON GAMEDAY", "THE {HN} ARE COMING", "{QB} > YOUR QB",
             "{QB} FOR PRESIDENT", "IT'S A GREAT DAY TO BE A {HEAD}", "{H} FOOTBALL: AGAINST ALL ODDS (AND {A})",
             "WE BELIEVE", "{HN} NATION IS AWAKE", "THIS PLACE. THIS TEAM. THIS DAY.",
             "OUR DEFENSE HAS A CURFEW FOR YOUR OFFENSE", "{QB} THROWS DIMES. WE MAKE CHANGE.",
             "LOUDEST PLACE IN AMERICA", "{H} TO THE PLAYOFF", "I HAVE BEEN WAITING MY WHOLE LIFE FOR TODAY",
             "WIN TODAY, SLEEP IN DECEMBER"],
    "life": ["MY PROFESSOR IS HERE TOO. HI, DR. PATEL.", "I TOLD MY BOSS I HAD A DENTIST APPOINTMENT",
             "THIS IS MY THIRD SIGN. THE FIRST TWO BLEW AWAY.", "I'VE BEEN AWAKE SINCE THURSDAY",
             "MOM SAID I COULD COME IF I WORE SUNSCREEN. I DID NOT.", "I SOLD MY TEXTBOOKS FOR GAS MONEY",
             "WILL TRADE ROOMMATE FOR SIDELINE PASS", "MY FIRST DATE WITH SARAH. SARAH, IS THIS GOING WELL?",
             "I BROUGHT MY GRANDPA. HE'S BEEN TO 61 OF THESE.", "I CAME FROM THE HOSPITAL. BABY #3 CAN WAIT.",
             "MY DAD'S BIRTHDAY. SAY HAPPY BIRTHDAY, DAD!", "I SKIPPED MY OWN BACHELOR PARTY FOR THIS",
             "STILL NO GIRLFRIEND. STILL HAVE GAMEDAY.", "MY KIDS THINK THIS IS A FIELD TRIP",
             "I PAINTED MY CAR FOR THIS"],
    "rival": ["{RIVAL} FANS ARE CRYING SOMEWHERE", "BEAT {A} TODAY, BEAT {RIVAL} FOREVER",
              "{RIVAL} WISHES THEY HAD THIS CROWD", "THIS SIGN WAS NOT APPROVED BY {RIVAL}",
              "{RIVAL}, TAKE NOTES"],
    "headgear": ["{COACH}: HEAD ON OR HEAD HOME", "PUT IT ON, {COACH}", "{COACH} IN THE {HEAD} HEAD = WORLD PEACE",
                 "{COACH}, MY GRANDMA MADE THAT HEAD. WEAR IT."],
}
SIGN_REPLIES_MORE = {
    "jab": [[("host", "{a}'s fans are behind the barrier over there. They're not laughing."), ("crowd", "(roaring)")],
            [("boom", "OOOOH. They came to fight today."), ("defender", "Fans or players?"), ("boom", "Everybody.")],
            [("defender", "If I'm {a}, I'm screenshotting that and showing my team."),
             ("coach", "Every coach alive would do the same.")],
            [("film", "Harsh. Accurate? We'll see."), ("crowd", "(cheering)")],
            [("coach", "That's a mean sign. I like it.")],
            [("host", "The {a} section just held up a sign that says 'SCOREBOARD.' It's 0-0."),
             ("boom", "That's a bold move at seven in the morning.")]],
    "hype": [[("host", "They mean it, too."), ("crowd", "(roaring)")],
             [("film", "I'll say this — there's evidence for it."), ("boom", "EVIDENCE!")],
             [("defender", "Nothing wrong with believing. You have to believe before anybody else does.")],
             [("boom", "Put that sign in the Hall of Fame."), ("host", "There's no sign Hall of Fame."),
              ("boom", "There should be.")],
             [("coach", "I've seen that kind of confidence before. Sometimes it's right.")]],
    "life": [[("host", "Somebody please check on that person after the show."), ("crowd", "(laughter)")],
             [("defender", "That's dedication. Questionable dedication, but dedication.")],
             [("boom", "I relate to this on a deep level."), ("host", "Of course you do.")],
             [("coach", "When I was that age I'd have done the same thing. Don't tell my mother.")],
             [("film", "I respect the commitment. I have questions about the priorities."),
              ("crowd", "(laughter)")],
             [("host", "Hello to whoever's watching at home who's about to see this. Sorry in advance."),
              ("crowd", "(laughter)")]],
    "rival": [[("defender", "They don't even play them today and they're still thinking about them."),
               ("coach", "That's how you know it's real.")],
              [("host", "The rivalry never takes a week off."), ("crowd", "(roaring)")]],
    "headgear": [[("coach", "(doesn't even look at the sign)"), ("crowd", "(chanting louder)"),
                  ("host", "He heard you. Trust me, he heard you.")],
                 [("coach", "We'll talk at the end of the show, young man."), ("crowd", "(roaring)")]],
}
CAST_SIGNS_MORE = {
    "boom": [("{BOOM} IS MY SPIRIT ANIMAL", [[("boom", "And you are MINE, sir."), ("crowd", "(roaring)")]]),
             ("{BOOM}, YOUR HAIR IS A LIE", [[("boom", "It is NOT a lie. It is an ongoing story."),
                                              ("crowd", "(laughter)")]]),
             ("{BOOM} FOR MAYOR", [[("boom", "I accept. First order of business: Campus Countdown every week, here."),
                                    ("host", "You can't be mayor, {boom_first}."), ("boom", "Watch me.")]])],
    "film": [("{FILM} HAS NEVER SMILED", [[("film", "I smile."), ("host", "When?"), ("film", "...Internally."),
                                           ("crowd", "(laughter)")]]),
             ("{FILM}, WHAT'S THE THIRD DOWN CONVERSION RATE OF LOVE?",
              [[("film", "About forty percent, honestly. Depends on the down and distance."), ("crowd", "(laughter)")]])],
    "defender": [("{DEFENDER} STILL HOLDS MY HS RECORD FOR BEING COOL", [[("defender", "I'll take it. I'll frame it."),
                                                                         ("crowd", "(cheering)")]]),
                 ("{DEFENDER}, HIT ME", [[("defender", "Sir, I'm retired."), ("boom", "He's not that retired."),
                                          ("crowd", "(laughter)")]])],
    "host": [("{HOST} HAS BEEN RIGHT ONCE", [[("host", "More than once. Twice, easily."), ("crowd", "(laughter)")]]),
             ("{HOST}, READ MY SIGN", [[("host", "I am reading your sign. This is me, reading your sign."),
                                        ("crowd", "(cheering)")]])],
    "coach": [("{COACH}, TEACH ME DISCIPLINE", [[("coach", "Step one: put the sign down and sit up straight."),
                                                 ("crowd", "(laughter)")]]),
              ("{COACH} WOULD BEAT YOUR COACH IN ARM WRESTLING", [[("coach", "He's not wrong."),
                                                                  ("boom", "Coach!"), ("coach", "He's not wrong, {boom_first}.")]])],
}

# ═══ Longer interviews ══════════════════════════════════════════════════════
# topic: (questions, [(answer, interviewer follow-up or None)])
# Follow-ups respond to that specific answer. {opp} {town} {stadium} {stat}
# {home_state} {mate} (a teammate) {hc} (his head coach) {riv} are filled in.

INTERVIEW_MORE = {
    "crowd": (["Have you ever played in front of a crowd like the one you'll see tonight?",
               "What's it like running out of that tunnel in {stadium}?"],
              [("It's the best feeling in the world. You feel it in your chest before you hear it.",
                "In your chest. I remember that feeling."),
               ("Honestly, the first time I almost fell down. My legs went numb.", "Did you tell anybody?"),
               ("You try not to look up. If you look up, you get emotional.", None)]),
    "opponent": (["What's the one thing {opp} does that worries you?", "How do you prepare for a team like {opp}?"],
                 [("Their front seven. They play fast and they play angry.", "Angry is a good word for them."),
                  ("Same as every week. But this week everybody paid a little closer attention in meetings.",
                   "Coaches notice that."),
                  ("Film, film, and more film. I've seen every snap they've played this year.",
                   "You and {film} should talk.")]),
    "season": (["You're {stat} this year. Did you expect this kind of season?",
                "Take me through your season so far — {stat}."],
               [("I expected to work. I didn't expect all of this. My teammates made it happen.",
                 "Your teammates would say you made it happen."),
                ("Honestly? Yes. I told my mom in the summer this would be the year.", "Did she believe you?"),
                ("I don't look at stats. My roommate does. He tells me every Sunday.", "Every Sunday?")]),
    "home": (["Back home in {home_state}, how many people are watching tonight?",
              "What does it mean to the folks in {home_state} to see you play in games like this?"],
             [("My whole town. They'll have it on at the barbershop, at the diner, everywhere.",
               "That's a lot of people counting on you."),
              ("My little brother's going to be watching. He's a freshman in high school. I play for him.",
               "He's lucky to have you."),
              ("It means everything. Nobody from my high school ever played on a stage like this.", None)]),
    "pressure": (["How do you sleep the night before a game like this?", "Is there pressure on you tonight?"],
                 [("Like a baby. I'm serious. I've never had trouble sleeping.", "That's rare. Most guys don't sleep."),
                  ("Pressure is a privilege. Coach says it every day.", "{hc} says that?"),
                  ("There's pressure. But it's the good kind. You want to be in these games.", None)]),
    "teammate": (["Who's a teammate people need to know about?", "Who's been the unsung hero of your season?"],
                 [("{mate}. He does everything right and never gets any credit.", "Why doesn't he get credit?"),
                  ("Our offensive line. All five of them. I'd buy them dinner every night if I could.",
                   "Linemen eat a lot. That's an expensive promise."),
                  ("{mate}. He was the first guy in the building every morning this summer.", None)]),
    "coach": (["What's {hc} like behind closed doors?", "What's the best thing {hc} has told you?"],
              [("Honestly, he's funnier than people think. But not during the week of a big game.",
                "When does he get funny again?"),
               ("He told me to stop playing to not lose and start playing to win. Changed my whole season.", None),
               ("He's demanding. Every single rep. But you know he cares.", "That's all a player wants.")]),
    "rival": (["What does {riv} mean to you personally?", "When did you first understand how big {riv} is?"],
              [("The first time I walked into the grocery store here and a lady told me not to lose it.",
                "Just a random lady?"),
               ("I grew up watching it. I know every big play from the last ten years.", "Name one."),
               ("It's the one game you can't take back. You carry it for a whole year.", None)]),
    "goal": (["Your program has big goals this year. Does the team talk about them?",
              "Everybody's talking about the goals set for this program. Do you feel them?"],
             [("We don't talk about the big stuff. We talk about Saturday. The big stuff takes care of itself.", None),
              ("Honestly? Yeah. We know what the standard is here. We want to meet it.", "What's the standard?"),
              ("We have them on the wall in the locker room. You can't miss them.", "Every day?")]),
    "film": (["How much film do you watch in a week?", "What did you see on film this week that got you excited?"],
             [("Probably fifteen hours. More in a week like this.", "{film} would like to meet you."),
              ("There's one thing they do on third down that I think we can take advantage of. That's all I'll say.",
               "Smart. Don't give it away on TV."),
              ("Mostly my own mistakes. I watch those twice.", None)]),
    "fun": (["Last one — what's your pregame meal?", "What's on your playlist before a game?",
             "If you weren't playing football, what would you be doing?"],
            [("Pancakes. Always pancakes. I don't know why and I'm not changing it now.", "Superstition?"),
             ("Old-school stuff. My dad's music. It calms me down.", None),
             ("Honestly? Probably teaching. My mom's a teacher. I'd coach high school ball.",
              "That's a great answer."),
             ("Chicken and rice. Every game since I was fourteen. My mom makes it at home too.", None)]),
}
FOLLOWUP_ANSWERS = [
    "(laughs) Yeah. Every single time.", "Honestly, yes. And I'm not ashamed of it.",
    "(smiles) I'll leave it at that.", "No comment. My mom might be watching.",
    "Every day. Twice on Fridays.", "(laughs) That's between me and him.",
]
INTERVIEW_CLOSERS = [
    "Good luck tonight.", "Go get it.", "Appreciate your time — have a great game.",
    "Thanks for sitting down with me. Big night ahead.", "We'll be watching.",
]

REASONS_MORE = {
    "talent": ["The best players usually win. {team} has more of them.", "I'm going with the better roster. {team}.",
               "When in doubt, pick the team with more Pro League players on it. That's {team}.",
               "{team} has recruited better for four years. That shows up in November.",
               "More speed, more size, more depth. {team}."],
    "qb": ["{qb} has been the best quarterback on the field all year, and I don't see that changing.",
           "In a close game, I want the better quarterback. That's {qb}.",
           "{qb}. Protects the ball, makes the throws. That's the pick.",
           "It's a quarterback league. {team} has the quarterback.",
           "{qb} is going to make three throws today that nobody else in this game can make."],
    "defense": ["Defense wins championships, and {team} plays the better defense.",
                "{team}'s front is going to live in the backfield all day.",
                "I trust {team}'s defense to make the stop that matters.",
                "Turnovers. {team}'s defense is going to get two of them.",
                "{team} doesn't give up big plays. Make them drive the length of the field. They won't."],
    "coach": ["{coach_name} is going to have them ready. I trust the coaching.",
              "The better-coached team wins close games. That's {team}.",
              "{team}'s staff makes the better halftime adjustments. That's the difference.",
              "{coach_name}'s teams don't make the dumb mistakes. That wins games like this."],
    "home": ["I'm not going against this crowd.", "You'd have to be crazy to pick against this place today.",
             "The noise alone is worth a touchdown.", "This crowd is going to cause three false starts.",
             "Home crowd, home team, easy pick."],
    "form": ["{team} is playing its best football right now.", "Hot team. Hot hand. {team}.",
             "{team} has been getting better every week. That's who you pick in November.",
             "I'm riding {team} until they give me a reason not to."],
    "upset": ["Call me crazy. I'm taking the upset.", "Everybody wants the favorite. I want the story.",
              "My gut says upset and my gut has been right before. Twice.", "I've got a feeling nobody else has."],
    "contrarian": ["Five guys picking the same team makes me nervous. I'll zig.",
                   "When everybody agrees, somebody's wrong. I'll take my chances on the other side."],
}

BANTER_MORE = [
    [("host", "{coach}, did you sleep on the bus again?"), ("coach", "I rest my eyes. It's different."),
     ("boom", "You snored for two hours, Coach."), ("coach", "Resting loudly.")],
    [("film", "I found a play on film this week that I've never seen before."), ("host", "What was it?"),
     ("film", "A triple reverse flea flicker."), ("boom", "Did it work?"), ("film", "It lost eleven yards."),
     ("boom", "Beautiful.")],
    [("defender", "My son asked me this week if I was faster than the guys playing today."),
     ("host", "What'd you tell him?"), ("defender", "I said yes."), ("film", "Were you?"),
     ("defender", "I said yes, {film_first}.")],
    [("boom", "I got a text from my mom during the last segment."), ("host", "What'd she say?"),
     ("boom", "\"Stop yelling.\""), ("crowd", "(laughter)"), ("boom", "I will NOT stop yelling, Mom.")],
    [("host", "{film}, how many spreadsheets did you bring today?"), ("film", "Three."),
     ("defender", "Three spreadsheets for one show?"), ("film", "One for each quarter. I combine the fourth.")],
    [("coach", "Somebody left a plate of cookies at the desk this morning."), ("boom", "That was me."),
     ("coach", "They were very good."), ("boom", "They were for the crowd."), ("coach", "They were very good, {boom_first}.")],
    [("defender", "I have a question for the desk. Best sideline you ever stood on?"),
     ("coach", "Mine. Any of them. I was on them."), ("boom", "Mine was the one I got kicked off of."),
     ("host", "You got kicked off a sideline?"), ("boom", "Two, technically.")],
    [("host", "We should mention — {boom} is wearing two different shoes today."),
     ("boom", "It's a statement."), ("film", "What's the statement?"), ("boom", "That I got dressed in the dark.")],
    [("film", "Did you know the average college football game has about 140 plays?"),
     ("boom", "Did you know I don't care?"), ("film", "I did know that, actually."), ("crowd", "(laughter)")],
    [("coach", "Kids today have it easy. When I played we had one water break. In August."),
     ("defender", "Coach, when you played they didn't have water."), ("coach", "We had a hose.")],
    [("host", "{defender}, what's the hardest hit you ever took?"),
     ("defender", "Honestly? From {boom} at a charity softball game."), ("boom", "I didn't see you!"),
     ("defender", "You were the catcher, {boom_first}.")],
    [("boom", "I've decided to start a podcast."), ("host", "About what?"), ("boom", "Me."),
     ("film", "That's already this show.")],
    [("film", "I want to formally apologize for my pick last week."), ("host", "Accepted."),
     ("film", "I wasn't done."), ("host", "We know. Accepted anyway.")],
    [("coach", "I got recognized at the airport yesterday."), ("boom", "That's great, Coach!"),
     ("coach", "The man thought I was his dentist.")],
    [("defender", "My old coach called me this week. Told me I talk too much on TV."),
     ("host", "Do you?"), ("defender", "I told him he talked too much in meetings. We're even.")],
    [("host", "{boom}, you've picked the home team how many weeks in a row?"), ("boom", "All of them, {host}."),
     ("host", "That's not a strategy."), ("boom", "It's a LIFESTYLE.")],
    [("film", "I charted the crowd noise this morning."), ("defender", "How?"),
     ("film", "Phone app. It hit a hundred and six decibels when {boom} walked out."), ("boom", "For ME?"),
     ("film", "Mostly at you.")],
    [("coach", "My wife told me not to put on the headgear today."), ("host", "Are you going to listen?"),
     ("coach", "I've been married forty-one years, {host}. I always listen. Then I do what I want.")],
]

COACH_STORIES_MORE = [
    [("coach", "My first head coaching job, the team bus broke down on the way to the game."),
     ("defender", "What'd you do?"), ("coach", "Borrowed a church van. Two trips."), ("boom", "Did you win?"),
     ("coach", "By thirty. Never had a team that loose again.")],
    [("coach", "I once had a quarterback who called his own plays. Wouldn't listen to me."),
     ("film", "Was he good?"), ("coach", "He was great. That's the problem. I couldn't bench him.")],
    [("coach", "Worst weather game I ever coached — sleet, both ways, all four quarters."),
     ("host", "Final score?"), ("coach", "3-2."), ("boom", "How is that a score?"),
     ("coach", "A field goal and a safety. Don't ask me which one we got.")],
    [("coach", "I had a player sneak a live goat into the locker room once. Before a rivalry game."),
     ("boom", "WHY?"), ("coach", "Nobody ever told me. We won, though. The goat stayed a week.")],
    [("coach", "Best recruiting visit I ever had: the kid's grandma made me eat three plates of food."),
     ("host", "Did he sign?"), ("coach", "He signed. Grandma made me promise I'd come back every Christmas."),
     ("defender", "Did you?"), ("coach", "Twelve years. She passed last spring. Best cook in Mississippi.")],
    [("coach", "My worst loss, I went home and my daughter asked me why I was sad."),
     ("host", "What did you tell her?"), ("coach", "I said we lost. She said, 'But you still get to coach.' "
                                                    "Nine years old. Smartest thing anybody's ever said to me.")],
    [("coach", "I called a fake punt on fourth and twenty-two once."), ("film", "Twenty-two?"),
     ("coach", "We needed something. The punter ran for twenty-three yards."), ("boom", "I love this story."),
     ("coach", "I never called it again. You only get one of those.")],
    [("coach", "I used to have a rule: no music in the locker room. My players hated it."),
     ("defender", "What changed?"), ("coach", "We lost three straight. I let them play music. We won eight straight."),
     ("coach", "I'm stubborn. I'm not stupid.")],
]
CROWD_CHALLENGES_MORE = [
    [("boom", "Left side of the lawn versus right side! Who's louder? Left side, GO!"), ("crowd", "(roaring — left side)"),
     ("boom", "Right side!"), ("crowd", "(deafening — right side)"), ("boom", "Right side wins! Sorry, left side!"),
     ("crowd", "(booing — left side)")],
    [("boom", "Everybody who drove more than five hours to be here, make some noise!"), ("crowd", "(roaring)"),
     ("boom", "More than ten hours!"), ("crowd", "(one guy screaming in the back)"),
     ("host", "That man deserves a medal.")],
    [("boom", "I need a volunteer to do the fight song with me. Solo."), ("crowd", "(a student raises her hand)"),
     ("boom", "Get up here!"), ("crowd", "(roaring as she sings every word)"), ("boom", "SHE KNOWS ALL THE WORDS, "
                                                                                           "{host}!")],
    [("boom", "Quiet! Everybody quiet! Total silence!"), ("crowd", "(complete silence for three seconds)"),
     ("boom", "NOW GO!"), ("crowd", "(explodes)"), ("host", "That was actually incredible.")],
]

# ═══ Guest pickers by region ════════════════════════════════════════════════
# Same one-line format as GUEST_PICKERS: (who they are, what they say, bias).
# Regional ones only appear at campuses in that part of the country.

GUESTS_REGIONAL = {
    "Southeast": [
        ("has run the same sweet tea stand outside the stadium since 1988", "Sweet tea and a sweet win.", "home"),
        ("is a bass fishing champion from just up the road", "I know when to set the hook. It's today.", "home"),
        ("is the preacher whose Sunday sermons include the Saturday score", "The Lord and I both have a pick.", "heart"),
        ("drove his boat to the game", "Parked it at the lake. Walked two miles. Worth it.", "home"),
        ("is a peanut farmer who hasn't missed a home opener in 40 years", "Forty years. One pick.", "home"),
        ("is the fifth-generation owner of a barbecue joint", "Sauce is secret. My pick isn't.", "home"),
        ("is a stock car driver from down the highway", "I don't lift off the gas. Neither do they.", "home"),
        ("is a college baseball legend from {state}", "Different sport, same heart.", "heart"),
    ],
    "South Central": [
        ("is a rodeo champion who rode in on a horse this morning", "The horse picked too. We agree.", "home"),
        ("is a Friday night lights coach whose team won state last year", "I know a tough team when I see one.", "chalk"),
        ("runs the best crawfish boil in the state", "Spicy food, spicy pick.", "home"),
        ("is an oil field worker who drove through the night", "Twelve hours on a rig, eight in a truck. Worth it.", "home"),
        ("owns a Texas-sized steakhouse with the team's logo on the menu", "Order the ribeye. Pick the {nick}.", "home"),
        ("is a cattle rancher whose herd is named after former players", "Bessie picked first. I'm with Bessie.", "home"),
        ("is a zydeco accordion player who opened the show", "Can't play without the {nick} winning.", "home"),
    ],
    "Midwest": [
        ("is a dairy farmer who got up at three to milk cows before driving here", "Cows are fine. Pick is easy.", "home"),
        ("coaches a six-man high school team in Arthur, Nebraska (population 145)", "Six men, one heart.", "heart"),
        ("is a snowplow driver who hasn't missed a home game in a blizzard", "Snow doesn't stop me. Nothing stops us.", "home"),
        ("is a corn farmer who carved the team logo into ten acres", "You can see it from space. Probably.", "home"),
        ("runs a supper club that's been open since 1946", "Friday fish fry, Saturday win.", "home"),
        ("is an ice fishing tournament winner", "Patience. That's how you win. Patience and the {nick}.", "chalk"),
        ("is the town's volunteer fire chief", "We put out fires. They start them.", "home"),
        ("is a retired autoworker who's had season tickets since 1971", "Built cars for 38 years. Built this pick in a second.", "home"),
    ],
    "Mountain": [
        ("is a ski patrol captain who drove down the mountain this morning", "Altitude doesn't bother us. Bothers them.", "home"),
        ("is a rancher who drove four hours through two mountain passes", "The mountains are on our side.", "home"),
        ("is a river guide who's rafted every rapid in the state", "Rough water ahead for the visitors.", "home"),
        ("is a rodeo clown with thirty years in the business", "I've dodged bulls. I can dodge a bad pick.", "coin"),
        ("is a smokejumper who fights wildfires every summer", "I jump into fire. This is easy.", "home"),
    ],
    "West": [
        ("is a big wave surfer who paddled in this morning", "Catch the wave, dude. The {nick} wave.", "home"),
        ("is a vineyard owner who named a wine after the team", "It's a good vintage. So is this team.", "home"),
        ("is a tech startup founder who flew in on his own plane", "I disrupt industries. They disrupt offenses.", "chalk"),
        ("is a fisherman who hauled in a record salmon last week", "Big fish, big game, big pick.", "home"),
        ("is a food truck owner famous for fish tacos", "Taco Tuesday, {nick} Saturday.", "home"),
        ("is a movie stuntman who's been set on fire eleven times", "I don't scare easy. Neither does this team.", "upset"),
    ],
    "Northeast": [
        ("is a lobsterman who drove down from the coast", "Pinch 'em early. That's the pick.", "home"),
        ("owns a pizzeria that's been open since 1952", "Best slice in the state and the best team.", "home"),
        ("is a firefighter from the city who's been here since dawn", "We don't back down. Neither do they.", "home"),
        ("is a maple syrup farmer who brought samples for the whole crew", "Sweet pick. Very sweet.", "home"),
        ("is a subway conductor who took the day off for the first time in six years", "Next stop: a win.", "home"),
        ("is a diner owner who's served every coach this program has had", "Coffee's always on. So's the {nick}.", "home"),
    ],
}
GUESTS_MORE = [
    ("is a twin who's been to every home game with her brother", "We never agree. Today we do.", "home"),
    ("is a marathon runner who ran here from the next town over", "Twenty-six miles. I'm not losing today.", "home"),
    ("is a middle school science teacher who predicted the score with a volcano", "The volcano knows.", "coin"),
    ("is the stadium organist for 34 years", "I've played every big moment. I'll play one more.", "home"),
    ("is a meteorologist who says the forecast calls for a blowout", "Hundred percent chance of domination.", "chalk"),
    ("is a crossword puzzle champion", "Seven letters, starts with W: winners. The {nick}.", "home"),
    ("is the host campus's longest-serving janitor", "I've cleaned up after every win. Let's make a mess tonight.", "home"),
    ("is a 102-year-old fan who attended her first game in 1941", "I've seen them all, honey. This is the one.", "heart"),
    ("is a golf pro who once caddied for a president", "Good lie, good read, good pick.", "chalk"),
    ("is a juggler who's been entertaining the tailgates all morning", "I've got three balls in the air and one pick.", "coin"),
    ("is a kid who wrote a letter to the head coach that got framed in the facility", "Coach wrote me back. That's a sign.", "home"),
    ("is a trucker who hauled the team's equipment here", "I know what's in that truck. It's a win.", "home"),
    ("is a wedding DJ who played the fight song at 300 receptions", "Three hundred first dances. One last dance.", "home"),
    ("is a paleontologist who dug up a dinosaur last summer", "I've studied extinction. The visitors are next.", "home"),
    ("is a professional eater with a world record in wings", "I can take down anything. So can this defense.", "home"),
    ("is a mail carrier whose route runs right past the stadium", "Special delivery: a win.", "home"),
    ("is an astronaut who took a team flag to the space station", "Out of this world. Just like this pick.", "chalk"),
    ("is a former walk-on kicker who made one field goal in four years", "One kick. One pick. Both good.", "heart"),
    ("is a barber who's given every starter a haircut this season", "They look good. They'll play good.", "home"),
    ("is an auctioneer", "Going once, going twice... sold to the {nick}!", "home"),
    ("is a school bus driver who got every kid on her route to wear team colors", "Forty-two kids can't be wrong.", "home"),
    ("is a comedian who got booed off stage here in 2019", "I'm back, and I'm picking the home team so you'll like me.", "home"),
    ("is a magician who made the rival's trophy disappear at a tailgate", "For my next trick, a win.", "home"),
    ("is an 11-year-old who won the campus spelling bee", "W-I-N. {school}.", "home"),
    ("is a beekeeper with 40 hives and one opinion", "The bees agree with me.", "coin"),
    ("is a nurse who worked a double shift to be here", "I've been awake for thirty hours. My pick is clear.", "home"),
    ("is a truck stop owner famous for his cinnamon rolls", "Big rolls, big win.", "home"),
    ("is a bowling alley owner who rolled a 300 last month", "Perfect game. Perfect pick.", "chalk"),
    ("is a violinist from the city symphony", "Every great piece has a big finish.", "heart"),
    ("is a war veteran and three-time grand marshal of the homecoming parade", "I've seen tough. This team is tough.", "home"),
    ("is the owner of a local hardware store that's sold out of team paint", "Out of paint. Full of hope.", "home"),
    ("is a TikTok cook whose game-day chili has ten million views", "Ten million people can't be wrong.", "home"),
    ("is a hot air balloon pilot who flew over the stadium at dawn", "I had the best view in town. Home team, easy.", "home"),
    ("is a small-town mayor with a population of 212", "All 212 of us agree.", "home"),
    ("is a professional mascot for a minor league baseball team", "Mascot to mascot, I respect the {nick}.", "home"),
    ("is a college student who has attended every class this semester", "Perfect attendance. Perfect pick.", "chalk"),
    ("is a retired judge", "I've heard all the evidence. The verdict is in.", "chalk"),
    ("is a chess grandmaster from {state}", "I see eleven moves ahead. The {nick} win in all of them.", "chalk"),
    ("is a fire-eater who performed at every tailgate this morning", "Hot pick coming.", "upset"),
    ("is the owner of the only bookstore in town", "Every good story has a twist. Here's mine.", "upset"),
]

# ═══ More interview questions (merged into INTERVIEW_MORE at load) ═════════
INTERVIEW_QUESTIONS_MORE = {
    "crowd": ["What do you hear when this place gets loud?", "Do you ever look up at the stands during a game?",
              "What's the loudest you've ever heard it in {stadium}?"],
    "opponent": ["If you could take one player from {opp}'s roster, who would it be?",
                 "What did your coaches emphasize about {opp} this week?", "Where does {opp} try to hurt you?",
                 "What's the matchup against {opp} you've circled?"],
    "season": ["What's been the biggest surprise of your season?", "What part of your game has grown the most this year?",
               "If you had to grade your season so far, what would you give yourself?"],
    "home": ["Who taught you the game back in {home_state}?", "What do you miss most about home during the season?",
             "Is there a coach back in {home_state} you still call?"],
    "pressure": ["What do you do in the hour before kickoff?", "Is there a moment this season you felt the pressure?",
                 "How do you block out the noise in a week like this?"],
    "teammate": ["Who's the funniest guy in your locker room?", "Who would you want with the ball on the last play?",
                 "Which young player on this roster is about to be a star?"],
    "coach": ["What did {hc} say to you after your worst game this year?", "How has {hc} changed you as a player?",
              "What would people be surprised to learn about {hc}?"],
    "rival": ["What's the first thing you think about when you hear {riv}?",
              "What does a win in {riv} buy you in this town?"],
    "goal": ["What would it mean to hit those goals this year?", "Which goal on that wall means the most to you?"],
    "film": ["What's the one clip from this season you'd show a recruit?", "What's the worst play you've ever watched "
                                                                             "of yourself on film?"],
    "fun": ["Who's the worst dancer on the team?", "What's the best thing you've eaten on a road trip?",
            "Who's got the worst taste in music in your locker room?", "What's your go-to video game on the road?",
            "If you could have dinner with anybody, who would it be?"],
}
FOLLOWUP_ANSWERS_MORE = [
    "(laughs) You'd have to ask him.", "Honestly? It surprised me too.", "That's the truth. I swear.",
    "(pauses) Yeah. I think about it a lot.", "Every week. It never gets old.", "My mom would say yes.",
    "(grins) I'm not allowed to say.", "Absolutely. No doubt about it.", "I'll tell you after the season.",
    "That stays in the locker room.", "Probably more than I should.", "(nods) That's exactly it.",
    "You'd have to see it to believe it.", "Every single time. Ask anybody.", "I wish I had a better answer.",
    "(laughs) Next question.", "That's a secret, and it's staying one.", "I'd do it all over again.",
]
INTERVIEW_CLOSERS_MORE = [
    "Best of luck tonight.", "Go make some memories.", "Enjoy it — you only get so many nights like this.",
    "We'll be watching. Good luck.", "Thanks for the time. Go get a win.", "Appreciate you. Big one tonight.",
    "Have fun out there.", "Go put on a show.", "Good luck — and save some for the fourth quarter.",
]

# ═══ Interviews, rebuilt: every question travels with its own answers ══════
# topic: [(question, [(answer, follow-up question or None, follow-up answer or None), ...]), ...]
INTERVIEW_QA = {
    "crowd": [
        ("What's it going to be like in {stadium} tonight?",
         [("Crazy. We feed off it. When it gets loud, we get faster.", "Faster?", "(laughs) It feels that way, anyway."),
          ("You can't hear the snap count, and you don't care. It's the best.", None, None)]),
        ("What's it like running out of that tunnel?",
         [("The first time, my legs went numb. I almost fell down.", "Did anybody notice?", "Our center did. He still brings it up."),
          ("You try not to look up. If you look up, you get emotional.", None, None)]),
        ("Do you ever look up at the stands during a game?",
         [("Once. Against my better judgment. I found my mom in about two seconds.", "Two seconds?",
           "She was the one standing on her seat.")]),
    ],
    "opponent": [
        ("What worries you most about {opp}?",
         [("Their front seven. They play fast and they play angry.", "Angry?", "You'll see what I mean in the first quarter."),
          ("How disciplined they are. They don't give you anything for free.", None, None)]),
        ("How did you prepare for {opp} this week?",
         [("{film_prep}", "Every snap?", "{film_prep_fa}"),
          ("Same as every week. But the meetings were a little quieter.", "Quieter how?", "Focused. Nobody was joking.")]),
        ("If you could take one thing from {opp}'s team, what would it be?",
         [("Their depth on the defensive line. They just keep rolling guys in.", None, None),
          ("Honestly? Their tailgates. I've heard stories.", "Good stories?", "Great stories. Not for TV.")]),
    ],
    "season": [
        ("You're at {stat} this year. Did you see a season like this coming?",
         [("I told my mom in the summer this would be the year.", "Did she believe you?", "She believes everything I say. She's my mom."),
          ("I expected to work. I didn't expect all of this.", None, None)]),
        ("What's been the biggest surprise of your season?",
         [("How close this team has gotten. We're a family now. I know that sounds like a cliché.",
           "Is it a cliché?", "Not in our locker room."),
          ("Winning the close ones. Last year we lost those. This year we find a way.", None, None)]),
        ("If you had to grade your season so far, what would you give yourself?",
         [("A B. I've left plays on the field. I know exactly which ones.", "Which ones?", "Coach knows. That's enough."),
          ("Incomplete. Ask me in December.", None, None)]),
    ],
    "home": [
        ("Back home in {home_state}, who's watching tonight?",
         [("My whole town. They'll have it on at the barbershop, the diner, everywhere.", "The barbershop?",
           "My barber's been cutting my hair since I was five. He's got a TV just for my games."),
          ("My little brother. He's a freshman in high school. I play for him.", None, None)]),
        ("Who taught you the game back in {home_state}?",
         [("My dad, in the backyard. He'd make me catch fifty passes before dinner.", "Every night?",
           "Every night. Even in the rain. Especially in the rain."),
          ("My high school coach. I still call him every Sunday.", None, None)]),
    ],
    "pressure": [
        ("How do you sleep the night before a game like this?",
         [("Like a baby. I've never had trouble sleeping.", "Never?", "Never. My roommate hates me for it."),
          ("I don't, really. I lie there and run plays in my head.", None, None)]),
        ("What do you do in the hour before kickoff?",
         [("Same thing every week. Same playlist, same stretch, same prayer.", "What's on the playlist?",
           "Old-school stuff. My dad's music."),
          ("I sit by myself for ten minutes. No phone, no music. Just breathe.", None, None)]),
        ("Is there pressure on you tonight?",
         [("Pressure's a privilege. Coach says it every day.", None, None),
          ("There's pressure. But it's the good kind. You want to be in these games.", None, None)]),
    ],
    "teammate": [
        ("Who's a teammate people need to know about?",
         [("{mate}. He does everything right and never gets any credit.", "Why no credit?",
           "He doesn't do anything flashy. He just never messes up."),
          ("{mate}. First guy in the building every morning this summer.", None, None)]),
        ("Who's the funniest guy in your locker room?",
         [("{mate}. Easy. He does impressions of all the coaches.", "Even the head coach?",
           "Especially the head coach. Don't tell him."),
          ("Our long snapper. Nobody knows his name, and he's the funniest person I've ever met.", None, None)]),
        ("Who do you want with the ball on the last play?",
         [("{mate}. No hesitation.", None, None),
          ("Me. And I think everybody on this team would say the same about themselves. That's the point.", None, None)]),
    ],
    "coach": [
        ("What's {hc} like behind closed doors?",
         [("Funnier than people think. But not during a week like this one.", "When does he get funny again?",
           "Sunday, if we win."),
          ("Demanding. Every single rep. But you always know he cares.", None, None)]),
        ("What's the best thing {hc} has ever told you?",
         [("Stop playing not to lose and start playing to win. It changed my whole season.", None, None),
          ("That he'd never lie to me. And he never has.", None, None)]),
    ],
    "rival": [
        ("What does {riv} mean to you?",
         [("A lady in the grocery store told me my first week here: 'Don't you dare lose that game.'",
           "A random lady?", "Never seen her before. Never seen her since. I think about her every year."),
          ("It's the one game you carry with you for a whole year, win or lose.", None, None)]),
        ("When did you first understand how big {riv} is?",
         [("I grew up watching it. I can tell you every big play from the last ten years.", "Name one.",
           "(grins) I'll tell you the one we make tonight.")]),
    ],
    "goal": [
        ("Your program has big goals on the wall. Does the team talk about them?",
         [("We don't talk about the big stuff. We talk about Saturday.", None, None),
          ("They're on the wall in the locker room. You walk past them every day.", "Does that add pressure?",
           "It adds purpose.")]),
    ],
    "film": [
        ("How much film do you watch in a week?",
         [("Probably fifteen hours. More in a week like this.", "{film_line}", "(laughs) I've seen his show."),
          ("Not as much as I should. Don't tell my position coach.", None, None)]),
        ("What's one clip from this season you'd show a recruit?",
         [("{clip}", None, None),
          ("Honestly, a block. Not a catch, not a run — a block. That's what winning looks like.", None, None)]),
    ],
    "fun": [
        ("Last one — what's your pregame meal?",
         [("Pancakes. Always pancakes. I don't know why and I'm not changing it now.", "Superstition?", "Tradition. It's different."),
          ("Chicken and rice. Every game since I was fourteen.", None, None)]),
        ("Last one — what's on your playlist before a game?",
         [("Old-school stuff. My dad's music. It calms me down.", None, None),
          ("Honestly? Country. The guys give me a hard time about it.", "Do you care?", "Not even a little.")]),
        ("Last one — if you weren't playing football, what would you be doing?",
         [("Teaching. My mom's a teacher. I'd coach high school ball, too.", None, None),
          ("I'd be a chef. I cook for the whole O-line on Sundays.", "The whole line?", "It's a lot of food.")]),
        ("Last one — who's the worst dancer on the team?",
         [("{mate}. By a lot. It's not close.", "Is he going to see this?", "I hope so."),
          ("Me. I know it. Everybody knows it.", None, None)]),
        ("Last one — if you could have dinner with anybody, who would it be?",
         [("My grandfather. He passed before I got here. He'd have loved this.", None, None),
          ("Honestly? My mom. I don't get home enough during the season.", None, None)]),
    ],
}

# ═══ Host lead-ins: used when a scene's first line doesn't set up its own topic ═
STORY_LEADS = {
    "rivalry": ["It's {riv}.", "Let's talk about {riv}.", "{riv} — the one they circle every year."],
    "unbeaten": ["Two unbeatens today.", "Nobody's lost yet — {h} or {a}.", "Unbeaten against unbeaten."],
    "top10": ["Top ten against top ten.", "Two top-ten teams on this field today.", "A top-ten showdown."],
    "ranked": ["Two ranked teams here.", "{A} and {H} — both ranked."],
    "upset_alert": ["No. {fav_rank} {fav} has to come into a tough spot today.", "Upset watch: {dog} hosting No. {fav_rank} {fav}."],
    "win_streak": ["{team} has won {n} straight.", "{team} comes in on a {n}-game win streak.", "That's {n} in a row for {team}."],
    "skid": ["{team} has lost {n} straight.", "{team} is on a {n}-game skid.", "It's been {n} losses in a row for {team}."],
    "riser": ["{team} jumped from No. {was} to No. {now} this week.", "{team} is up to No. {now} after sitting at {was}."],
    "faller": ["{team} fell from No. {was} to {now}.", "{team} took a tumble this week — No. {was} down to {now}."],
    "bounce_back": ["{team} is coming off a {score} loss to {opp}.", "{team} lost to {opp} last week, {score}."],
    "hot_seat": ["The seat's getting warm for {coach} at {team}.", "{coach} and {team} are {rec}, and people are talking."],
    "new_coach": ["{coach} is in his first season at {team}.", "Year one for {coach} at {team}: {rec}."],
    "coach_return": ["{coach} is facing {old}, where he used to coach.", "{coach} used to work at {old}. Now he's across the field."],
    "injury": ["{team} will be without {player} today.", "Injury news: {player} is out for {team}."],
    "heisman": ["{team}'s {player} is No. {hrank} in our Golden Helmet poll — {stats}.", "Golden Helmet watch: {player}, {stats} for {team}."],
    "qb_duel": ["The quarterbacks: {aqb} and {hqb}.", "What a quarterback matchup — {aqb} against {hqb}."],
    "shootout": ["Two of the best offenses in the country: {hppg} and {appg} points a game.", "Points could come in bunches today."],
    "defense_duel": ["Two great defenses: {hpapg} and {apapg} points allowed a game.", "This could be a low-scoring one."],
    "conf_race": ["The {conf} race: {h} at {hcrec}, {a} at {acrec}.", "Big one in the {conf} standings."],
    "playoff": ["Playoff implications all over this one.", "The playoff picture runs through this game."],
    "revenge": ["Last time these two met, in {year}, {winner} won {ws}-{ls}.", "{loser} hasn't forgotten {year}: {winner} won {ws}-{ls}."],
    "rematch": ["These two met in {year}. {winner} won it, {ws}-{ls}.", "A rematch of {year}, when {winner} beat {loser} {ws}-{ls}."],
    "goal_rival": ["Beating {rival} is written right into {team}'s program goals.", "{team}'s athletic director put beating {rival} on the list."],
    "trap": ["{team} has {next} next week.", "Here's a trap game — {team}, with {next} coming up next week."],
    "visit_curse": ["The last time Campus Countdown came to {town}, {h} lost.", "A little Campus Countdown history in {town}: the home team lost last time."],
    "bowl_push": ["{team} is {rec} — one win from bowl eligibility.", "Bowl watch: {team} needs one more win."],
    "big_favorite": ["{fav} comes in a heavy favorite over {dog}.", "On paper, {fav} is a lot better than {dog}."],
    "first_visit": ["First ever Campus Countdown in {town}.", "This is our first trip to {h}."],
    "return_visit": ["We're back in {town}.", "Campus Countdown returns to {town}."],
}
