"""
gameday_scenes.py — Everything the Campus Countdown crew says, written as whole scenes.

A scene is a list of (speaker, line). Speakers: host, film, coach, boom,
defender, crowd, player, reporter, guest. Every line in a scene answers the
one before it — nothing is drawn from a pool on its own.

Placeholders available everywhere:
  {H} {A}        home / away with rank ("No. 7 Provo")   {h} {a} plain school names
  {hn} {an}      nicknames                            {town} "Provo"  {state}
  {stadium}      where the show is                    {hrec} {arec} records
  {hc} {ac}      head coaches                         {hqb} {aqb} quarterbacks
  {host} {film} {coach} {boom} {defender}             the cast's last names
Storyline scenes also get that storyline's own fields (listed per section).
"""

# ═══ Openers ═══════════════════════════════════════════════════════════════
OPENERS = {
    "default": [
        [("crowd", "\"{chant}\""),
         ("host", "Good morning from {town}! {H} hosts {A}, and the lawn has been full since before sunrise."),
         ("boom", "{host}, I got here at four. FOUR. There were already people here."),
         ("host", "Did they let you in?"), ("boom", "Eventually."), ("crowd", "(laughter)")],
        [("host", "Welcome to Campus Countdown, live from {stadium} in {town}!"), ("crowd", "(roaring)"),
         ("host", "{A} at {H}. {arec} against {hrec}. Let's get to work."),
         ("film", "{film_snaps}"),
         ("host", "Of course you have.")],
        [("host", "Good morning, everybody. It's Campus Countdown, and we are in {town}."),
         ("defender", "I walked around campus last night. Every porch in town has a {hn} flag on it."),
         ("host", "You walked around?"), ("defender", "Signed about four hundred things."),
         ("crowd", "(cheering)"), ("host", "{A} at {H} — let's go.")],
        [("crowd", "\"{chant}\""), ("host", "Listen to that. That's {town} at seven in the morning."),
         ("coach", "I coached a lot of games against crowds like this one. Never liked it. Loved it, but never liked it."),
         ("host", "That makes no sense, Coach."), ("coach", "It will by tonight.")],
    ],
    "rivalry": [
        [("crowd", "\"{chant}\""), ("host", "It's {riv}, and Campus Countdown is in {town}!"),
         ("boom", "{host}, you know what this game means around here? People plan WEDDINGS around this game."),
         ("host", "Around it, {boom_first}? Or during it?"), ("boom", "...Both. I've been to one."), ("crowd", "(laughter)")],
        [("host", "Good morning from {town}. Records don't matter today. It's {riv}."),
         ("coach", "Records never matter in this one. I learned that the hard way."),
         ("host", "How hard?"), ("coach", "Hard enough that I still won't talk about it."),
         ("crowd", "(cheering)")],
        [("crowd", "(booing — a {a} bus just drove past the set)"),
         ("host", "And there's your answer to how they feel about {a} here. Welcome to {riv}!"),
         ("defender", "I played in a rivalry like this. You don't sleep the night before. You just stare at the ceiling."),
         ("host", "And today?"), ("defender", "Today I just stare at {boom}.")],
    ],
    "opener": [
        [("host", "College football is BACK! Good morning from {town}!"), ("crowd", "(roaring)"),
         ("boom", "Eight months, {host}. EIGHT MONTHS I've been waiting for this."),
         ("host", "What did you do all summer?"), ("boom", "Waited for this."),
         ("host", "{A} at {H} to open the season. Let's go.")],
        [("host", "Welcome to the first Campus Countdown of the season, live from {town}."),
         ("film", "Week one is my favorite. Nobody knows anything yet. Everybody thinks they do."),
         ("host", "Including you?"), ("film", "Especially me.")],
    ],
    "first_visit": [
        [("host", "For the first time ever, Campus Countdown is in {town}!"), ("crowd", "(deafening)"),
         ("defender", "Look at this. They've been waiting a long time for us to show up."),
         ("host", "{h} earned this one. {hrec}, and a lot of people finally noticed."),
         ("boom", "And we're never leaving. I've already looked at houses.")],
        [("host", "Good morning from {town} — our first trip here, and what a welcome."),
         ("coach", "I coached against {h} once, years ago. They didn't have a crowd like this back then."),
         ("host", "What changed?"), ("coach", "They started winning. That's what changes crowds.")],
    ],
    "return_visit": [
        [("host", "We're back in {town}! Last time Campus Countdown was here was {last_year}."),
         ("boom", "And I've been dreaming about the barbecue ever since."),
         ("film", "He brought it up on the plane. Twice."), ("crowd", "(laughter)")],
        [("host", "Good morning from {town}, and it's good to be back."),
         ("defender", "The last time we were here, this place was loud. This is louder."),
         ("host", "And there's more on the line this time.")],
    ],
    "postseason": [
        [("host", "Good morning from {town}! It's the {round}, and every one of these games is win or go home."),
         ("coach", "December football. You can feel it — every snap weighs a little more."),
         ("host", "{A} and {H}. One of them is still playing next week.")],
        [("crowd", "(roaring)"), ("host", "It's the {round}, and Campus Countdown is live from {town}!"),
         ("boom", "{host}, this is the best time of year and I will not be taking questions."),
         ("host", "Nobody asked you a question."), ("boom", "And I'm not answering it.")],
    ],
}

# ═══ Storyline scenes ══════════════════════════════════════════════════════
# Extra fields per kind are noted. Each scene reads top to bottom as one talk.

STORY = {
    "rivalry": [  # {riv}
        [("host", "{coach}, what's different about a game like {riv}?"),
         ("coach", "Talent matters less. The team that handles the emotion better wins. Somebody's going to get a "
                   "penalty in the first quarter they'll regret for a year."),
         ("defender", "And that somebody is usually a guy who's been talking about this game since July."),
         ("host", "So — watch the talkers?"), ("defender", "Watch the talkers.")],
        [("film", "I charted the last few years of {riv}. The team that wins the rushing battle almost always wins "
                  "the game."),
         ("boom", "That's it? Run the ball?"), ("film", "Run the ball and don't turn it over."),
         ("boom", "I could've told you that."), ("film", "You didn't, though.")],
        [("host", "What does a win in {riv} do for a season?"),
         ("coach", "It can save one. I've seen coaches go 7-5 and keep their jobs because they won this game."),
         ("boom", "And I've seen coaches go 10-2 and get yelled at in the grocery store because they lost it."),
         ("crowd", "(cheering)")],
    ],
    "unbeaten": [  # {n} combined wins
        [("host", "Two unbeatens. {n} wins between them. One of them leaves tonight with a loss."),
         ("film", "And the one who loses isn't finished — that's the thing people forget. One loss doesn't end "
                  "anything in this format."),
         ("defender", "Tell that to the locker room. Nobody in there thinks one loss is fine."),
         ("host", "Fair."), ("film", "It's fine. It just doesn't feel fine.")],
        [("boom", "I love undefeated versus undefeated. Somebody's zero has to go!"),
         ("coach", "The pressure's on whoever's been winning ugly. Those teams feel it first."),
         ("host", "Who's been winning uglier?"),
         ("coach", "I'll tell you at the final pick."), ("crowd", "(booing)"), ("coach", "Patience.")],
    ],
    "top10": [
        [("host", "Top ten against top ten. {H} and {A}. This one gets remembered in December."),
         ("film", "Everybody talks about the playoff committee watching. They are. This is a résumé game for both."),
         ("defender", "For one of them. The loser's résumé just gets a big red mark on it."),
         ("film", "Not if it's close. Close losses to good teams travel.")],
        [("boom", "I've been waiting all year for this one, {host}."),
         ("host", "You said that about last week's game."), ("boom", "And I MEANT it then too."),
         ("coach", "He means it every week. It's his best quality and his worst.")],
    ],
    "ranked": [
        [("host", "{A} and {H} — both ranked, both trying to prove it belongs there."),
         ("film", "One of these rankings is a little soft. I think we find out which one today."),
         ("host", "Which one do you think?"), ("film", "Hold that thought until the picks.")],
    ],
    "upset_alert": [  # {fav} {dog} {fav_rank}
        [("host", "Upset alert — No. {fav_rank} {fav} on the road, and {dog} is unranked and not scared."),
         ("boom", "This is the one! This is the one, {host}! I can feel it!"),
         ("film", "You feel it every week."), ("boom", "And one of these weeks I'll be right."),
         ("defender", "He was right three weeks ago."), ("boom", "THANK you.")],
        [("coach", "I'll tell you why {fav} should be nervous. Ranked teams on the road against a team with "
                   "nothing to lose — that's where upsets live."),
         ("host", "What does {dog} have to do?"),
         ("coach", "Win the turnover battle and keep it close into the fourth. Then the crowd does the rest."),
         ("crowd", "(roaring)")],
    ],
    "win_streak": [  # {team} {n}
        [("host", "{team} has won {n} straight."),
         ("defender", "And they're not just winning — they're getting better every week. That's what scares me."),
         ("film", "The numbers say the same thing. Their third-down defense has gotten better every game."),
         ("host", "So the streak is real."), ("film", "The streak is very real.")],
        [("boom", "{n} in a row for {team}, baby! Can't stop it!"),
         ("coach", "Streaks end. They always end. The question is whether it ends today."),
         ("boom", "Not today, Coach."), ("coach", "That's what every streak says.")],
    ],
    "skid": [  # {team} {n}
        [("host", "{team} has lost {n} in a row. How do you stop that?"),
         ("coach", "You simplify. Fewer plays, fewer calls. Let your players stop thinking and start hitting."),
         ("defender", "And you find one guy in the locker room who refuses to let it happen again."),
         ("host", "Do they have that guy?"), ("defender", "We're about to find out.")],
        [("film", "{team}'s problem is turnovers. They're giving the ball away in every one of these losses."),
         ("boom", "So stop doing that."), ("film", "Thank you, {boom_first}. I'll pass it along.")],
    ],
    "riser": [  # {team} {was} {now}
        [("host", "{team} jumped from {was} to {now} in the poll this week."),
         ("film", "And the voters were right. That's not a fluke — they've been underrated all year."),
         ("coach", "Now they get the target on their back. That's the part nobody warns you about."),
         ("host", "Harder to climb or harder to stay?"), ("coach", "Harder to stay. Every time.")],
    ],
    "faller": [  # {team} {was} {now}
        [("host", "{team} was No. {was} last week. Now they're {now}."),
         ("defender", "That's a gut check. The way they respond today tells you everything about that locker room."),
         ("boom", "I'd be MAD. I'd come out swinging."), ("defender", "That's why they don't let you coach.")],
    ],
    "bounce_back": [  # {team} {opp} {score}
        [("host", "{team} is coming off a {score} loss to {opp}."),
         ("coach", "The week after a loss is the most important week of a season. You find out who your leaders are."),
         ("film", "And on tape, it wasn't as bad as the score. They moved the ball — they just didn't finish."),
         ("host", "Fixable?"), ("film", "Very fixable.")],
        [("defender", "Losing to {opp} last week has to sting. I'd want to hit somebody."),
         ("boom", "You always want to hit somebody."), ("defender", "It's a good quality in a safety.")],
    ],
    "hot_seat": [  # {team} {coach} {rec}
        [("host", "The seat is warm for {coach} at {team}. They're {rec}."),
         ("coach", "I've sat in that seat. You stop sleeping. You second-guess every call."),
         ("defender", "The players know, too. They read everything."),
         ("coach", "And the good ones play harder for you because of it. That's the only thing that saves you.")],
        [("film", "The tape on {team} isn't as bad as the record. They lose close games."),
         ("host", "Does that matter to an athletic director?"),
         ("film", "It should. It usually doesn't."), ("coach", "It doesn't. Trust me.")],
    ],
    "new_coach": [  # {team} {coach} {rec}
        [("host", "{coach}'s first season at {team}: {rec} so far."),
         ("coach", "Year one is about getting them to believe you. The wins come after that."),
         ("film", "You can already see his fingerprints on the offense. Different tempo, different identity."),
         ("host", "Good different?"), ("film", "Promising different.")],
    ],
    "coach_return": [  # {team} {coach} {old}
        [("host", "{coach} used to coach at {old}. Today he's on the other sideline."),
         ("boom", "That's awkward, {host}. That's like running into your ex at the grocery store."),
         ("coach", "It's worse. Your ex doesn't have ninety thousand people booing you."),
         ("crowd", "(booing)"), ("host", "And there it is.")],
        [("defender", "Coaching against your old school — he knows half their playbook, and they know half of his."),
         ("coach", "He knows their players, too. Recruited some of them. That's the part that gets personal."),
         ("host", "Advantage?"), ("coach", "Slight. Until the ball's kicked.")],
    ],
    "injury": [  # {team} {player} {pos}
        [("host", "{team} will be without {player} today."),
         ("film", "That's a big hole. The offense changes when he's not out there."),
         ("coach", "Next man up. Every coach says it. The good programs actually mean it."),
         ("host", "Is {team} a good program?"), ("coach", "We'll find out in the fourth quarter.")],
    ],
    "heisman": [  # {team} {player} {hrank} {stats}
        [("host", "{team}'s {player} — No. {hrank} in our Golden Helmet poll — {stats} this season."),
         ("film", "What I love is how he plays on third down. He's at his best when it matters most."),
         ("defender", "As a defender, you just hope he has a bad day. You can't stop a guy like that."),
         ("host", "A big game today, and he's right in the middle of the race."),
         ("boom", "Golden Helmets are won in games like this, {host}!")],
        [("coach", "I've coached a Golden Helmet finalist. You know what separates them? They don't care about it."),
         ("host", "Does {player} care about it?"), ("coach", "Not if he's smart.")],
    ],
    "qb_duel": [  # {hqb} {aqb} {hstats} {astats}
        [("host", "The quarterback matchup: {aqb} with {astats}, {hqb} with {hstats}."),
         ("film", "Two different styles. {aqb} wins from the pocket. {hqb} wins when the play breaks down."),
         ("defender", "Which is the one I'd rather face?"), ("film", "Neither, if you've got a choice."),
         ("defender", "I never got a choice.")],
        [("film", "If you gave me one of these two quarterbacks to win a game in the fourth quarter..."),
         ("boom", "Which one?"), ("film", "I'm not telling you until the final pick."),
         ("boom", "You're the WORST.")],
    ],
    "shootout": [  # {hppg} {appg}
        [("host", "{h} averages {hppg} points a game. {a} averages {appg}."),
         ("boom", "Oh, we're getting a track meet, {host}!"),
         ("defender", "Somebody has to get a stop. Just one. The first defense to get a stop wins."),
         ("coach", "He's right. In a game like this one punt is like an interception.")],
    ],
    "defense_duel": [  # {hpapg} {apapg}
        [("host", "{h} allows {hpapg} a game. {a} allows {apapg}."),
         ("defender", "Now we're talking. A real football game. Every yard's going to cost something."),
         ("film", "Field position decides this one. Watch the punters."),
         ("boom", "I was a punter!"), ("film", "We know, {boom_first}.")],
    ],
    "conf_race": [  # {conf} {hcrec} {acrec}
        [("host", "In the {conf} race, {h} is {hcrec} and {a} is {acrec}. This one decides a lot."),
         ("coach", "Conference games in October are playoff games. That's how you have to treat them."),
         ("film", "Lose this one and you need help the rest of the way. Nobody wants to need help."),
         ("host", "Winner controls its own path.")],
    ],
    "playoff": [
        [("host", "Playoff implications all over this one."),
         ("film", "The committee's going to have this game on in the room. You can't hide a result like this."),
         ("defender", "The winner's in great shape. The loser is sweating for a month."),
         ("boom", "I'd be sweating right now. I AM sweating right now."), ("host", "It's warm out, {boom_first}.")],
    ],
    "revenge": [  # {winner} {loser} {ws} {ls} {year}
        [("host", "Last time these two met, in {year}, {winner} won {ws}-{ls}."),
         ("defender", "{loser} hasn't forgotten. You don't forget a game like that."),
         ("coach", "I'd have that score on the locker room wall all week."), ("host", "Would you?"),
         ("coach", "Every coach does. The ones who say they don't are lying.")],
    ],
    "rematch": [  # {winner} {loser} {ws} {ls} {year}
        [("host", "These two met in {year} — {winner} won that one {ws}-{ls}."),
         ("film", "Different teams now, though. Half those starters are gone."),
         ("boom", "The grudge isn't gone!"), ("film", "The grudge is never gone.")],
    ],
    "goal_rival": [  # {team} {rival}
        [("host", "One more thing on {team}: beating {rival} is written right into the athletic director's goals."),
         ("coach", "That's the job. You can win nine games, but lose this one and you hear about it."),
         ("defender", "That's real pressure."), ("coach", "That's college football.")],
    ],
    "first_visit": [
        [("film", "First Campus Countdown ever for {h}. That's a big deal for recruiting — every kid in the state is "
                  "watching this."),
         ("host", "Can one morning really help a program?"),
         ("film", "It can help a program sign a kid it would've never gotten a phone call back from.")],
    ],
    "return_visit": [
        [("boom", "Last time we were here, {host}, I lost my voice by nine a.m."),
         ("host", "We noticed."), ("boom", "I'm pacing myself today."),
         ("crowd", "(roaring)"), ("boom", "...I'M NOT PACING MYSELF TODAY!")],
        [("host", "We've been to {town} before. {defender}, what do you remember?"),
         ("defender", "The noise. And the food. Mostly the food."), ("coach", "They remember us too. They "
                                                                            "remember who we picked.")],
        [("film", "Last time we were in {town}, the home team won. The crowd hasn't let me forget I picked against them."),
         ("crowd", "(booing, cheerfully)"), ("film", "I hear you. I hear all of you.")],
        [("boom", "{host}, the same guy who sold me a hat last time just sold me another hat."),
         ("host", "How many hats do you need?"), ("boom", "From {town}? All of them.")],
    ],
}

# ═══ Signs ═════════════════════════════════════════════════════════════════
# Each sign type has its own replies, and a reply always answers that kind of sign.
# Cast signs are answered by the cast member they're about.

SIGNS = {
    "jab": ["{A} FANS: THE EXIT IS THAT WAY", "{A} HAS NEVER SEEN A CROWD LIKE THIS", "{AN} = OVERRATED",
            "WELCOME TO {TOWN}. YOUR SEASON ENDS HERE.", "{A}'S DEFENSE HASN'T SEEN A REAL QB YET",
            "{A} FANS, WE SAVED YOU A SEAT (IN THE PARKING LOT)"],
    "hype": ["{QB} FOR HEISMAN", "{TOWN} RUNS ON {HN} FOOTBALL", "UNDEFEATED & UNDERRATED" ,
             "{HN} BY 21", "BELIEVE IN {H}", "THIS IS {HN} COUNTRY"],
    "life": ["MY WIFE SAID PICK HER OR GAMEDAY. SEE YOU SATURDAY, LINDA.", "I SKIPPED MY MIDTERM FOR THIS",
             "HI MOM, PLEASE DON'T TELL DAD I SKIPPED CLASS", "I DROVE 9 HOURS AND I'D DO IT AGAIN",
             "GRANDMA'S 80TH BIRTHDAY. SHE'S HERE. SHE PICKED {H}.", "FIRST GAMEDAY, FIRST SIGN, FIRST SUNBURN",
             "I NAMED MY DOG AFTER OUR QB. MY DOG IS FASTER."],
    "rival": ["ONE MORE {RIVAL} LOSS AND I'M RENAMING MY KID", "EVEN {RIVAL} FANS ARE WATCHING THIS",
              "WE'D RATHER LOSE THIS THAN BEAT {RIVAL}. JUST KIDDING. WE'RE BEATING BOTH."],
    "headgear": ["{COACH}, WEAR THE {HEAD} HEAD OR DON'T COME BACK", "{COACH}: THE HEAD. THE HEAD. THE HEAD."],
    "cast": {  # (sign, [its replies])
        "boom": [("{BOOM} OWES ME $20", [[("boom", "I do NOT owe you twenty dollars. It was ten. I'll pay it after the show."),
                                          ("crowd", "(laughter)")]]),
                 ("{BOOM}: MARRY ME (SERIOUSLY)", [[("boom", "Ma'am, I'm flattered, but I'm working."), ("crowd", "(laughter)")],
                                                  [("boom", "Is that a yes if I pick the home team?"), ("crowd", "(roaring)")]]),
                 ("{BOOM} PUNTED WORSE THAN MY GRANDMA", [[("boom", "Your grandma never punted in a snowstorm!"),
                                                          ("film", "Neither did you, allegedly."), ("crowd", "(laughter)")]])],
        "film": [("{FILM}, SHOW US THE FILM", [[("film", "I brought the film. It's in my bag. I'll show anyone who asks."),
                                               ("host", "Nobody asked, {film_first}."), ("film", "Someone will.")]]),
                 ("{FILM} HAS WATCHED MORE TAPE THAN BLOCKBUSTER", [[("film", "That's fair. That's very fair."),
                                                                    ("boom", "He's not even arguing!")]])],
        "defender": [("{DEFENDER} SIGNED MY FOREHEAD IN 2015", [[("defender", "I remember that! You were fourteen!"),
                                                                ("crowd", "(cheering)")]]),
                     ("{DEFENDER} STILL OWES ME AN INTERCEPTION", [[("defender", "I paid in full on Saturdays, sir."),
                                                                   ("crowd", "(roaring)")]])],
        "host": [("{HOST}, SAY HI TO MY MOM", [[("host", "Hi, Mom. Whoever you are. He looks like he's eating well."),
                                               ("crowd", "(laughter)")]]),
                 ("MY DOG HAS A BETTER PICK RECORD THAN {HOST}", [[("host", "Your dog is welcome to take my chair."),
                                                                  ("boom", "I'd like to hire your dog.")]])],
        "coach": [("{COACH} > YOUR COACH", [[("coach", "(nods once, very seriously)"), ("crowd", "(cheering)")]]),
                  ("COACH {COACH} RECRUITED MY DAD. DAD SAID NO. DAD REGRETS IT.",
                   [[("coach", "Tell your father I've forgiven him."), ("crowd", "(laughter)")]])],
    },
}
SIGN_REPLIES = {
    "jab": [[("defender", "That's a sign that's going to age one way or the other by the fourth quarter today.")],
            [("boom", "Oh, they're not being nice today! I love it!"), ("crowd", "(roaring)")],
            [("film", "The {a} fans behind the barrier are reading that one right now."),
             ("crowd", "(booing — in the {a} section's direction)")],
            [("coach", "I'd have that one in my team meeting. Bulletin board material.")]],
    "hype": [[("film", "Bold. The numbers are in the same neighborhood, I'll give them that.")],
             [("boom", "YES. Believe it! I believe it!"), ("crowd", "(cheering)")],
             [("defender", "{a}'s players are going to see that on social media by lunch.")],
             [("coach", "Confidence. I like it. Now go play like it.")]],
    "life": [[("defender", "Linda deserves better, man."),
              ("boom", "Linda's watching right now. Linda — he loves you. He just loves this more."),
              ("crowd", "(laughter)")],
             [("host", "Somebody's going to be in trouble at home tonight."),
              ("boom", "Worth it!"), ("crowd", "(cheering)")],
             [("coach", "Young man, I hope that was worth it."), ("crowd", "(the sign holder nods vigorously)")],
             [("film", "Commitment. You can't teach that.")]],
    "rival": [[("host", "{rival} isn't even playing here today and they still got a sign."),
               ("defender", "That's how you know it's a real rivalry.")],
              [("boom", "Even when they're not here, they're HERE!"), ("crowd", "(roaring)")]],
    "headgear": [[("coach", "(stands up, points at the sign) We'll see, young man. We'll see."),
                  ("crowd", "\"{HEAD} HEAD! {HEAD} HEAD!\"")],
                 [("coach", "I'll wear what I wear."), ("crowd", "(booing)"),
                  ("coach", "...Nobody's ever booed me into anything."), ("crowd", "(louder booing)"),
                  ("host", "They're trying, Coach.")]],
}
SIGN_LEADS = ["Let's see what they brought. Front row —", "Over on the left:", "Way in the back —",
              "Right behind the desk:", "My favorite so far:", "This one's been up since five a.m.:",
              "Up on somebody's shoulders:", "Oh, look at this one —"]

# ═══ Interviews: questions and the answers that go with them ═══════════════
INTERVIEW = {
    "crowd": (["What's it going to be like in {stadium} tonight?", "Have you ever heard it louder than it'll be tonight?"],
              ["It's going to be crazy. We feed off it. When it gets loud, we get faster.",
               "Honestly? I can't wait. You can't hear the snap count and you don't care."]),
    "opponent": (["What stands out about {opp} on film?", "What do you respect most about {opp}?"],
                 ["They don't make mistakes. We can't either.",
                  "They're physical. We've got to match that from the first snap.",
                  "They're well coached. You can tell they'll be ready."]),
    "season": (["You're {stat} this year. What's been working?", "{stat} so far. What's clicked for you?"],
               ["Honestly, it's the guys around me. I'm just doing my job.",
                "Film. I've watched more tape this year than ever. I know where I'm supposed to be.",
                "The coaches put me in the right spots. I just try not to waste them."]),
    "home": (["You're from {home_state}. Who's coming to watch?", "What would a big game mean to folks back in {home_state}?"],
             ["My whole family's driving in. My grandma hasn't missed a home game.",
              "Everybody back home. My high school coach is going to be here too.",
              "It'd mean everything. That's where it started for me."]),
    "pressure": (["How do you handle a week like this?", "Do you feel the pressure of a game like this?"],
                 ["Same as any week. Same routine, same meals, same everything.",
                  "Pressure's a privilege. Coach says that every day, and he's right.",
                  "I try not to think about it. The game's the same size field."]),
}

# ═══ Why an analyst picked a team — keyed to what actually drove his pick ═══
REASONS = {
    "talent": ["{team} just has more players. Top to bottom, it's a better roster.",
               "Talent wins in the end. {team} has more of it.",
               "Look at the depth chart. {team} is better at more spots."],
    "qb": ["It's the quarterback. {qb} is the best player on the field.",
           "{qb} gives {team} the edge. He doesn't make the mistake that loses you a game.",
           "Quarterback play. I trust {qb} in the fourth quarter."],
    "defense": ["{team}'s defense is going to take something away and make them one-dimensional.",
                "Defense travels. {team} has the best unit on the field.",
                "{team} is going to win this game without the ball."],
    "coach": ["I trust the coaching. {team}'s staff is going to have the better plan.",
              "{coach_name} is going to out-coach the other guy. Simple as that.",
              "Discipline. {team} doesn't beat itself."],
    "home": ["Look around! You don't lose in front of this!", "This crowd is worth a touchdown.",
             "Home field. That's the whole pick. Home field."],
    "form": ["{team} has been rolling. You don't bet against a team playing like that.",
             "Momentum. {team} is the hotter team right now.",
             "{team} has found ways to win all year. I'm not stopping now."],
    "qb_backup": ["{qb} has been waiting for this chance. I think he's ready for it.",
                  "Backup or not, {qb} knows that offense. {team} doesn't miss a beat.",
                  "I've seen {qb} in practice film. He can play. {team}.",
                  "{team} built the whole week around {qb}. They'll protect him and run the ball.",
                  "Next man up. {qb} gets his shot, and I think he takes it."],
    "upset": ["I'm taking the upset. I've got a feeling.", "Everybody else is picking the favorite. Not me."],
    "contrarian": ["Everybody on this desk is picking the same team. That makes me nervous. I'm going the other way."],
}

# ═══ Optional segments ═════════════════════════════════════════════════════
COACH_STORIES = [
    [("coach", "I'll tell you a story. My second year as a head coach, we're up six with a minute left."),
     ("host", "Uh oh."), ("coach", "I call a timeout to ice their kicker. On an extra point."),
     ("film", "That's not how—"), ("coach", "I KNOW that's not how it works, {film_first}. I was thirty-four."),
     ("crowd", "(laughter)")],
    [("coach", "Best pregame speech I ever gave was four words long."), ("boom", "What were they?"),
     ("coach", "\"Go hit somebody. Hard.\""), ("boom", "That's five words."), ("coach", "Go hit somebody hard."),
     ("boom", "...Still five."), ("coach", "It worked either way.")],
    [("coach", "I once had a kicker who threw up before every game. Every single game."),
     ("defender", "Was he any good?"), ("coach", "Never missed an extra point in four years."),
     ("boom", "So the lesson is—"), ("coach", "The lesson is we kept a bucket on the sideline.")],
]
CROWD_CHALLENGES = [
    [("boom", "All right, {town}! I want to hear the loudest {chant} you've ever done! On three!"),
     ("boom", "One... two... THREE!"), ("crowd", "\"{chant}\" (deafening)"),
     ("boom", "{host}, I think my ears are bleeding."), ("host", "That's a you problem.")],
    [("boom", "I need somebody to come up here and do my job for thirty seconds!"),
     ("host", "{boom_first}, that's not—"), ("boom", "You! In the {hn} hat! Get up here!"),
     ("crowd", "(roaring as a fan climbs up to the desk)"), ("host", "We're going to get fined for this."),
     ("boom", "Sir, the floor is yours. Thirty seconds. Go."),
     ("fan", "(grabs the mic) {h} by a million! And {host}, you look great in person!"),
     ("host", "...He can stay."), ("crowd", "(roaring)")],
]


# ═══ Transitions — how the show moves from one segment to the next ═════════
# Spoken hand-offs instead of on-screen headers. Each is a tiny scene.
TRANSITIONS = {
    "THE SIGNS": [
        [("host", "Let's see what this crowd brought today.")],
        [("host", "These folks have been busy with poster board. Let's read a few.")],
        [("boom", "{host}, we HAVE to talk about these signs."), ("host", "All right, all right. A few signs.")],
        [("host", "Before we get to the football — the signs. There are some good ones out there.")],
        [("defender", "{host}, have you seen some of these signs?"), ("host", "I have. Let's share a few.")],
        [("host", "I've been reading signs over your shoulder all morning, {boom_first}. Let's show everybody.")],
        [("host", "Let's take a look out at the lawn.")],
        [("film", "Can we do signs? I've been staring at one for ten minutes."), ("host", "Let's do signs.")],
        [("host", "First, a little tour of the artwork out there.")],
    ],
    "THE MATCHUP": [
        [("host", "All right, let's get to the football.")],
        [("host", "Enough fun for a minute. Let's talk about this game.")],
        [("coach", "Can we talk about the actual game now?"), ("host", "Let's do it, Coach.")],
        [("host", "So what's this one really about? Let's dig in.")],
        [("host", "There's a lot going on in this game. Let's start breaking it down.")],
        [("host", "Let's talk about why we came to {town}.")],
        [("film", "{host}, I've got notes. A lot of notes."), ("host", "Let's hear them. Let's get into this game.")],
        [("host", "{A} at {H}. Let's get into it.")],
        [("host", "Okay. Down to business.")],
    ],
    "THE FILM ROOM": [
        [("host", "{film}, you've been itching to show us something. Take us to the film room.")],
        [("host", "Let's go to the tape. {film}?")],
        [("host", "{film} has been in the film room since Tuesday. What'd you find?")],
        [("film", "I want to show everybody something I saw on tape."), ("host", "Go ahead.")],
        [("host", "Time to get into the details. {film}, what's on the tape?")],
        [("host", "{film}, break it down for us.")],
        [("host", "You've been waiting all morning for this, {film}. The floor's yours.")],
        [("boom", "Uh oh. {film_first} has the clicker."), ("host", "{film}, go ahead.")],
    ],
    "DEFENDER TO WATCH": [
        [("host", "{defender}, who's your defender to watch?")],
        [("host", "{defender}, give us a defender to keep an eye on.")],
        [("host", "Who's the defensive player that decides this, {defender}?")],
        [("host", "{defender}, you've got a guy you want us watching.")],
        [("defender", "Can I talk defense for a minute?"), ("host", "Please. Who's your guy?")],
        [("host", "Let's talk about the other side of the ball. {defender}?")],
        [("host", "{defender}, somebody on defense is going to change this game. Who?")],
        [("boom", "Let Darius talk defense before he explodes."), ("host", "{defender}, who are you watching?")],
    ],
    "COACH'S CORNER": [
        [("host", "Coach, you've got that look. You've got a story.")],
        [("host", "Coach, you were telling me something during the break. Tell everybody.")],
        [("boom", "Coach, tell them the one you told me on the bus."), ("coach", "Which one?"),
         ("boom", "Any of them.")],
        [("host", "Coach has been quiet. That usually means a story's coming.")],
        [("host", "Before we move on — Coach, you've got one for us, don't you?")],
        [("defender", "Coach, this game reminds you of something. I can tell."), ("coach", "It does, actually.")],
        [("film", "Coach, is this where you tell a story from 1987?"), ("coach", "1989, {film_first}. Sit down.")],
        [("host", "Coach, give us something from the old days.")],
    ],
    "BOOM'S CROWD CHALLENGE": [
        [("boom", "Hold on. Hold on. I need something from this crowd.")],
        [("boom", "{host}, give me thirty seconds with these people."), ("host", "Here we go.")],
        [("host", "{boom_first}'s standing up. That's never good.")],
        [("boom", "Everybody on your feet! I don't care if you're already on your feet!")],
        [("host", "{boom_first}, you're climbing on the desk again."), ("boom", "I have to, {host}.")],
        [("boom", "{town}! I have a job for you!")],
        [("defender", "He's got that look, {host}."), ("host", "{boom_first}, what are you doing?"),
         ("boom", "Something beautiful.")],
        [("host", "{boom_first}'s grabbing a megaphone. I didn't know we had a megaphone.")],
    ],
    "LAST WEEK": [
        [("host", "Before we move on, let's settle last week.")],
        [("host", "A little housekeeping from last Saturday.")],
        [("host", "Let's revisit last week's big pick, shall we?")],
        [("film", "Are we doing last week?"), ("host", "We're doing last week.")],
        [("boom", "Please don't bring up last week."), ("host", "We're bringing up last week.")],
        [("host", "Quick look back before we look ahead.")],
        [("host", "Let's not forget where we were a week ago.")],
        [("defender", "I'd like the record to show something about last week."), ("host", "Go ahead.")],
    ],
    "UPSET ALERT": [
        [("host", "Somewhere today, a ranked team is in trouble. {boom}, you've found one.")],
        [("boom", "{host}, I've got an upset for you."), ("host", "Of course you do.")],
        [("host", "Every week we go looking for an upset. Here's this week's candidate.")],
        [("host", "Before the picks — {boom_first}'s been waving a piece of paper at me. What is it?"),
         ("boom", "An upset, {host}.")],
        [("host", "Let's find a ranked team that should be nervous today.")],
        [("film", "I'm guessing {boom_first} has an upset."), ("boom", "{boom_first} DOES have an upset.")],
        [("host", "Upset watch. {boom}, where are we looking?")],
        [("host", "One game outside {town} everybody should keep an eye on.")],
    ],
    "STATE OF THE SEASON": [
        [("host", "Let's zoom out. There's a lot going on in this sport right now.")],
        [("host", "Before we go any further — the big picture. Some things have happened this season that we have to talk about.")],
        [("film", "Can we talk about the rest of the country? Because it's been wild."), ("host", "It has. Let's do it.")],
        [("host", "The state of the season. Let's start with the one everybody's texting me about.")],
        [("coach", "I've been watching a lot of film from around the country this week."), ("host", "Let's hear it, Coach.")],
    ],
    "TODAY'S TAILGATE": [
        [("host", "And now, the segment the whole crew actually looks forward to.")],
        [("coach", "Is it tailgate time? Tell me it's tailgate time."), ("host", "It's tailgate time, Coach.")],
        [("host", "Something smells incredible, and I'm told it's coming from our next segment.")],
        [("defender", "I've been smelling smoke all morning."), ("host", "That's our next segment.")],
        [("host", "Let's go out to the lots.")],
    ],
    "AROUND THE COUNTRY": [
        [("host", "Let's go around the country — there's a lot more football today than just this one.")],
        [("host", "Let's look at the rest of today's board.")],
        [("film", "Can we talk about some of the other games today? There are some good ones."), ("host", "Let's do it.")],
        [("host", "A quick tour of what else is on today.")],
    ],
    "AROUND THE LEAGUE": [
        [("host", "Let's take a quick trip around the country.")],
        [("host", "Let's check in on the rest of college football.")],
        [("host", "A lot happened last week. Let's catch up.")],
        [("host", "Before we go any further, a look around the league.")],
        [("host", "Let's see what's going on outside {town}.")],
        [("host", "Meanwhile, in the rest of the country...")],
        [("film", "Can we talk about last week's results? I have thoughts."), ("host", "Let's go around the country.")],
        [("host", "Time to zoom out a little.")],
    ],
    "ONE-ON-ONE": [
        [("host", "Let's hear from one of the players in today's game.")],
        [("host", "One of today's stars sat down with us this week.")],
        [("host", "We got some time with one of the key players in this game.")],
        [("host", "Let's go inside one of these locker rooms.")],
        [("host", "Before the picks, a conversation worth hearing.")],
        [("host", "We wanted you to hear from somebody who's actually playing today.")],
        [("host", "Enough of us talking. Let's hear from a player.")],
        [("boom", "Can we hear from somebody who actually plays?"), ("host", "Funny you should ask.")],
    ],
    "FROM THE SIDELINE": [
        [("host", "Let's get the latest from the sideline.")],
        [("host", "Our sideline reporter has been with both teams this week.")],
        [("host", "Let's check in with our reporter on the field.")],
        [("host", "Time for the notes from inside both programs.")],
        [("host", "What are we hearing from the two sidelines?")],
        [("host", "Let's go down to the field for the latest.")],
        [("host", "Our reporter spent the week with both staffs.")],
        [("host", "Let's get some news from the field.")],
    ],
    "THE DESK": [
        [("host", "We've got a couple of minutes. Let's have some fun.")],
        [("host", "Quick break from the football.")],
        [("host", "Before we get serious again —")],
        [("host", "All right, a little fun before the picks.")],
        [("host", "Let's catch our breath for a second.")],
        [("host", "Before the picks, a few things from the desk.")],
        [("host", "Okay, the desk has something going on. I can tell.")],
    ],
    "THE PICKS": [
        [("host", "All right. The picks.")],
        [("host", "Let's get to the picks.")],
        [("host", "It's time. Everybody's picks.")],
        [("host", "Picks time. Let's see who's brave today.")],
        [("host", "Let's go around the country with our picks.")],
        [("boom", "Is it picks time?"), ("host", "It's picks time.")],
        [("host", "Now the part everybody complains about. The picks.")],
        [("film", "I've changed my picks four times this morning."), ("host", "Well, lock them in. Picks.")],
    ],
    "THE GUEST PICKER": [
        [("host", "Before the big one, we've got a special guest.")],
        [("host", "Time to meet today's guest picker.")],
        [("host", "Every week, somebody from the community joins us. Here's this week's.")],
        [("host", "We've got a guest on the desk today.")],
        [("boom", "Is it guest picker time? I love guest picker time."), ("host", "It is.")],
        [("host", "Somebody very important to this town is joining us.")],
        [("host", "One more voice before we finish.")],
        [("host", "Let's bring up our guest.")],
    ],
    "THE FINAL PICK": [
        [("host", "And now, the pick everybody came for.")],
        [("host", "It's time for the big one.")],
        [("boom", "Is it time?"), ("host", "It's time.")],
        [("host", "We saved the best for last.")],
        [("host", "All right. The game that brought us here.")],
        [("host", "Here we go. Everybody knows what's next.")],
        [("crowd", "(the chant starts before anybody says a word)"), ("host", "They know what time it is.")],
        [("host", "Last one. The biggest one.")],
    ],
}


# ═══ Setups — the host states the fact before a scene that assumes it ═══════
# Used only when a scene doesn't open with its own storyline fact.
SETUPS = {
    "rivalry": ["It's {riv}.", "This is {riv}, and it means something different.", "{riv} — the game this whole town circles."],
    "unbeaten": ["Two unbeaten teams, {n} wins between them.", "Nobody's beaten either of these teams yet.",
                 "Zero losses on both sides."],
    "top10": ["Top ten against top ten.", "Two top-ten teams, one field.", "This one's got two teams in the top ten."],
    "ranked": ["{A} and {H}, both ranked.", "Two ranked teams today."],
    "upset_alert": ["No. {fav_rank} {fav} walks into a tough spot against {dog}.",
                    "Unranked {dog} gets No. {fav_rank} {fav} at home.", "{dog} has a ranked team in its building today."],
    "win_streak": ["{team} has won {n} straight.", "{n} in a row for {team}.", "{team} comes in riding a {n}-game winning streak."],
    "skid": ["{team} has lost {n} in a row.", "{n} straight losses for {team}.", "{team} is trying to stop a {n}-game skid."],
    "riser": ["{team} jumped from {was} to {now} in the poll.", "{team} climbed to No. {now} this week."],
    "faller": ["{team} slid from No. {was} to {now}.", "{team} dropped out of the top spots this week — from {was} to {now}."],
    "bounce_back": ["{team} lost to {opp} last week, {score}.", "{team} is coming off a {score} loss to {opp}."],
    "hot_seat": ["The seat is warm for {coach} at {team} — they're {rec}.", "{coach} and {team} are {rec}, and people are talking."],
    "new_coach": ["It's year one for {coach} at {team}. They're {rec}.", "{coach}'s first season at {team}: {rec}."],
    "coach_return": ["{coach} used to coach at {old}. Today he's on the other sideline.",
                     "{coach} faces {old}, his former school."],
    "injury": ["{team} will be without {player} today.", "No {player} for {team} today."],
    "heisman": ["{team}'s {player} is No. {hrank} in our Golden Helmet poll — {stats}.",
                "Golden Helmet watch: {player}, {team}, {stats}."],
    "qb_duel": ["The quarterbacks: {aqb} with {astats}, {hqb} with {hstats}.", "{aqb} against {hqb}."],
    "shootout": ["{h} scores {hppg} a game. {a} scores {appg}.", "Two offenses averaging {hppg} and {appg} points."],
    "defense_duel": ["{h} allows {hpapg} a game, {a} allows {apapg}.", "Two of the stingiest defenses around."],
    "conf_race": ["In the {conf}, {h} is {hcrec} and {a} is {acrec}.", "This is a {conf} race game."],
    "playoff": ["Playoff implications all over this one.", "The playoff picture runs right through here."],
    "revenge": ["Last time these two met, in {year}, {winner} won {ws}-{ls}.", "{loser} lost this matchup {ws}-{ls} in {year}."],
    "rematch": ["These two met in {year} — {winner} won {ws}-{ls}."],
    "goal_rival": ["Beating {rival} is written right into {team}'s program goals."],
    "first_visit": ["It's Campus Countdown's first visit to {town}."],
    "return_visit": ["We were last here in {last_year}."],
    "trap": ["{team} has {next} on deck next week.", "Next week, {team} plays {next}. Today, it's this."],
    "visit_curse": ["The last time Campus Countdown came to {town}, {h} lost."],
    "bowl_push": ["{team} is {rec} — one win from bowl eligibility."],
    "big_favorite": ["{fav} comes in as a big favorite over {dog}.", "On paper, {fav} is a lot better than {dog}."],
}
# The fields that mean a scene already states its fact.
KEY_FIELDS = {"rivalry": ("riv",), "unbeaten": ("n",), "upset_alert": ("fav", "dog"), "win_streak": ("n",),
              "skid": ("n",), "riser": ("was", "now"), "faller": ("was", "now"), "bounce_back": ("opp", "score"),
              "hot_seat": ("rec", "coach"), "new_coach": ("rec", "coach"), "coach_return": ("old",),
              "injury": ("player",), "heisman": ("player",), "qb_duel": ("hqb", "aqb"),
              "shootout": ("hppg", "appg"), "defense_duel": ("hpapg", "apapg"), "conf_race": ("conf",),
              "revenge": ("winner", "loser", "year"), "rematch": ("year",), "goal_rival": ("rival",),
              "trap": ("next",), "visit_curse": (), "bowl_push": ("rec",), "big_favorite": ("fav", "dog"),
              "top10": (), "ranked": (), "playoff": (), "first_visit": (), "return_visit": ("last_year",)}


# ═══ Postseason ═════════════════════════════════════════════════════════════
OPENERS["title"] = [
    [("crowd", "(both fan bases, already loud)"), ("host", "Good evening from {town}! It's the national championship."),
     ("coach", "Sixteen weeks. Every one of them was for tonight."), ("host", "{A} and {H}. One more game.")],
    [("host", "Welcome to the final Campus Countdown of the season, live from {stadium}!"),
     ("boom", "{host}, I don't want this season to end."), ("host", "It ends tonight, {boom_first}."),
     ("boom", "I KNOW. That's why I'm sad.")],
    [("host", "It all comes down to this. Campus Countdown, live from {town}, for the national championship."),
     ("defender", "Every kid in both of these locker rooms dreamed about this night."),
     ("film", "And every one of them is trying not to think about it right now.")],
    [("host", "Good evening, everybody. One game left. {A}. {H}. For everything."),
     ("coach", "I coached in one of these. I don't remember a single thing anybody said to me that week."),
     ("host", "Not one thing?"), ("coach", "Not one. I remember the confetti.")],
]
STORY["stakes"] = [  # {round} {stakes}
    [("host", "This is the {round}. {stakes}"),
     ("coach", "Everything you did since January was for games like this one."),
     ("defender", "And nobody remembers the teams that lose them.")],
    [("film", "It's the {round}. The film says one thing, and the moment says another."),
     ("host", "What does the moment say?"), ("film", "That the team that plays loose wins.")],
    [("boom", "The {round}, {host}! Can you FEEL it?"), ("host", "{stakes}"),
     ("boom", "That's what I feel!")],
    [("defender", "Games like this, the best players have to be the best players. No hiding."),
     ("coach", "You find out who wants the ball. Some guys don't, this time of year.")],
    [("host", "{stakes} {coach}, how do you prepare for a week like this?"),
     ("coach", "Same as any other week. You'd be amazed how hard that is."),
     ("film", "The routine is the whole secret.")],
    [("film", "At this point in the season, both of these teams know exactly who they are."),
     ("host", "No surprises?"), ("film", "One surprise, maybe. Somebody always has one play saved.")],
    [("coach", "There's a feeling in the locker room before a game like this. It's quiet. Scary quiet."),
     ("boom", "I'd be screaming."), ("coach", "That's why you were a punter, {boom_first}.")],
    [("host", "{stakes}"), ("defender", "One team goes home with a trophy. The other goes home."),
     ("host", "Simple as that."), ("defender", "Simple as that.")],
]
SETUPS["stakes"] = ["{stakes}", "This is the {round}. {stakes}"]
KEY_FIELDS["stakes"] = ("round", "stakes")
